// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=3dba491d2c997e183aa6e11bb4c4af84b3cdf355$
//

#ifndef CEF_INCLUDE_CAPI_CEF_ACCESSIBILITY_HANDLER_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_ACCESSIBILITY_HANDLER_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_values_capi_versions.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_accessibility_handler_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *on_accessibility_tree_change)(struct _cef_accessibility_handler_0_t* self, struct _cef_value_0_t* value);
  void (CEF_CALLBACK *on_accessibility_location_change)(struct _cef_accessibility_handler_0_t* self, struct _cef_value_0_t* value);
} cef_accessibility_handler_0_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_ACCESSIBILITY_HANDLER_CAPI_VERSIONS_H_
