// Copyright (c) 2024 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=dce7493fc618caf7a722a4e273c86f5c41b24519$
//

#ifndef CEF_INCLUDE_CAPI_CEF_DEVTOOLS_MESSAGE_HANDLER_DELEGATE_CAPI_H_
#define CEF_INCLUDE_CAPI_CEF_DEVTOOLS_MESSAGE_HANDLER_DELEGATE_CAPI_H_
#pragma once

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_dialog_handler_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

///
/// Callback structure for info bar.
///
typedef struct _cef_info_bar_callback_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Allow to continue or not.
  ///
  void(CEF_CALLBACK* allow)(struct _cef_info_bar_callback_t* self, int allow);
} cef_info_bar_callback_t;

///
/// Implement this structure to handle devtools message.
///
typedef struct _cef_dev_tools_message_handler_delegate_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Called when devtools request to open file chooser.
  ///
  int(CEF_CALLBACK* show_file_chooser)(
      struct _cef_dev_tools_message_handler_delegate_t* self,
      cef_file_dialog_mode_t mode,
      const cef_string_t* title,
      const cef_string_t* default_file_path,
      cef_string_list_t accept_filters,
      int capture,
      cef_string_list_t mime_filters,
      struct _cef_file_dialog_callback_t* callback);

  ///
  /// Called when devtools request to show info bar.
  ///
  void(CEF_CALLBACK* show_info_bar)(
      struct _cef_dev_tools_message_handler_delegate_t* self,
      const cef_string_t* message,
      const cef_string_t* path,
      struct _cef_info_bar_callback_t* callback);

  ///
  /// Called when devtools request to display in front.
  ///
  int(CEF_CALLBACK* bring_to_front)(
      struct _cef_dev_tools_message_handler_delegate_t* self);

  ///
  /// Called when devtools request to close browser window.
  ///
  int(CEF_CALLBACK* close_window)(
      struct _cef_dev_tools_message_handler_delegate_t* self);

  ///
  /// Called when devtools request to display in front.
  ///
  int(CEF_CALLBACK* active_dev_tools_window)(
      struct _cef_dev_tools_message_handler_delegate_t* self);
} cef_dev_tools_message_handler_delegate_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_DEVTOOLS_MESSAGE_HANDLER_DELEGATE_CAPI_H_
