// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=603628cc5b659fa094d154f747647c421d5304f2$
//

#ifndef CEF_INCLUDE_CAPI_CEF_FILE_UTIL_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_FILE_UTIL_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

CEF_EXPORT int cef_create_directory(const cef_string_t* full_path);
CEF_EXPORT int cef_get_temp_directory(cef_string_t* temp_dir);
CEF_EXPORT int cef_create_new_temp_directory(const cef_string_t* prefix, cef_string_t* new_temp_path);
CEF_EXPORT int cef_create_temp_directory_in_directory(const cef_string_t* base_dir, const cef_string_t* prefix, cef_string_t* new_dir);
CEF_EXPORT int cef_directory_exists(const cef_string_t* path);
CEF_EXPORT int cef_delete_file(const cef_string_t* path, int recursive);
CEF_EXPORT int cef_zip_directory(const cef_string_t* src_dir, const cef_string_t* dest_file, int include_hidden_files);
CEF_EXPORT void cef_load_crlsets_file(const cef_string_t* path);

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_FILE_UTIL_CAPI_VERSIONS_H_
