// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=18bb156133f20345f996b918276b5d1f1f788b47$
//

#ifndef CEF_INCLUDE_CAPI_CEF_UNRESPONSIVE_PROCESS_CALLBACK_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_CEF_UNRESPONSIVE_PROCESS_CALLBACK_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_base_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_unresponsive_process_callback_0_t {
  cef_base_ref_counted_t base;
  void (CEF_CALLBACK *wait)(struct _cef_unresponsive_process_callback_0_t* self);
  void (CEF_CALLBACK *terminate)(struct _cef_unresponsive_process_callback_0_t* self);
} cef_unresponsive_process_callback_0_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_UNRESPONSIVE_PROCESS_CALLBACK_CAPI_VERSIONS_H_
