// Copyright (c) 2024 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=acb10ab8be4ebd3f9aefd90f9db072163ce0ad84$
//

#ifndef CEF_INCLUDE_CAPI_CEF_ADSBLOCK_MANAGER_CAPI_H_
#define CEF_INCLUDE_CAPI_CEF_ADSBLOCK_MANAGER_CAPI_H_
#pragma once

#include "include/capi/cef_base_capi.h"
#include "include/capi/cef_callback_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

///
/// Structure used for managing adsblock's rules.
///
typedef struct _cef_ads_block_manager_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Set Ads Block ruleset file, containing easylist rules.
  ///
  void(CEF_CALLBACK* set_ads_block_rules)(struct _cef_ads_block_manager_t* self,
                                          const cef_string_t* rulesFile,
                                          int replace);

  ///
  /// Add items to Ads Block Disallowed list.
  ///
  void(CEF_CALLBACK* add_ads_block_disallowed_list)(
      struct _cef_ads_block_manager_t* self,
      cef_string_list_t domainSuffixes);

  ///
  /// Remove items from Ads Block disallowed list.
  ///
  void(CEF_CALLBACK* remove_ads_block_disallowed_list)(
      struct _cef_ads_block_manager_t* self,
      cef_string_list_t domainSuffixes);

  ///
  /// Clear Ads Block disallowed list.
  ///
  void(CEF_CALLBACK* clear_ads_block_disallowed_list)(
      struct _cef_ads_block_manager_t* self);

  ///
  /// Add items to Ads Block Allowed list.
  ///
  void(CEF_CALLBACK* add_ads_block_allowed_list)(
      struct _cef_ads_block_manager_t* self,
      cef_string_list_t domainSuffixes);

  ///
  /// Remove items from Ads Block allowed list.
  ///
  void(CEF_CALLBACK* remove_ads_block_allowed_list)(
      struct _cef_ads_block_manager_t* self,
      cef_string_list_t domainSuffixes);

  ///
  /// Clear Ads Block allow list.
  ///
  void(CEF_CALLBACK* clear_ads_block_allowed_list)(
      struct _cef_ads_block_manager_t* self);
} cef_ads_block_manager_t;

///
/// Returns the global adsblock manager.
///
CEF_EXPORT cef_ads_block_manager_t* cef_ads_block_manager_get_global(
    struct _cef_completion_callback_t* callback);

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_ADSBLOCK_MANAGER_CAPI_H_
