// Copyright (c) 2024 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=e7855cf0ed0599fdc5f3c608595d15700b61c18b$
//

#ifndef CEF_INCLUDE_CAPI_CEF_LOAD_COMMITTED_DETAILS_CAPI_H_
#define CEF_INCLUDE_CAPI_CEF_LOAD_COMMITTED_DETAILS_CAPI_H_
#pragma once

#include "include/capi/cef_base_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

///
/// Structure used to represent the details of a committed navigation entry.
///
typedef struct _cef_load_committed_details_t {
  ///
  /// Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  /// Returns true (1) when the main frame was navigated. False means the
  /// navigation was a sub-frame.
  ///
  int(CEF_CALLBACK* is_main_frame)(struct _cef_load_committed_details_t* self);

  ///
  /// Returns true (1) if the navigation haapped without changing document.
  /// Example of same document navigations are: * reference fragment navigations
  /// * pushState/replaceState * same page history navigation
  ///
  int(CEF_CALLBACK* is_same_document)(
      struct _cef_load_committed_details_t* self);

  ///
  /// Returns true (1) if the committed entry has replaced the existing one.
  ///
  int(CEF_CALLBACK* did_replace_entry)(
      struct _cef_load_committed_details_t* self);

  ///
  /// Returns the type of navigation that just occurred.
  ///
  cef_navigation_entry_type_t(CEF_CALLBACK* get_navigation_type)(
      struct _cef_load_committed_details_t* self);

  ///
  /// Returns the url of the current navigation.
  ///
  // The resulting string must be freed by calling cef_string_userfree_free().
  cef_string_userfree_t(CEF_CALLBACK* get_current_url)(
      struct _cef_load_committed_details_t* self);
} cef_load_committed_details_t;

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_LOAD_COMMITTED_DETAILS_CAPI_H_
