// Copyright (c) 2022 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=d2a63576b59c75e748b5a725af9a4337414c82b9$
//

#ifndef CEF_INCLUDE_CAPI_CEF_DATA_BASE_CAPI_H_
#define CEF_INCLUDE_CAPI_CEF_DATA_BASE_CAPI_H_
#pragma once

#include "include/capi/cef_base_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

///
// Structure used for managing web data base.
///
typedef struct _cef_data_base_t {
  ///
  // Base structure.
  ///
  cef_base_ref_counted_t base;

  ///
  // clear all http auth data
  ///
  void(CEF_CALLBACK* delete_http_auth_credentials)(
      struct _cef_data_base_t* self);

  ///
  // get whether there has any http auth data.
  ///
  int(CEF_CALLBACK* exist_http_auth_credentials)(struct _cef_data_base_t* self);

  ///
  // save http auth data.
  ///
  void(CEF_CALLBACK* save_http_auth_credentials)(struct _cef_data_base_t* self,
                                                 const cef_string_t* host,
                                                 const cef_string_t* realm,
                                                 const cef_string_t* username,
                                                 const char* password);

  ///
  // get http auth data by host and realm.
  ///
  void(CEF_CALLBACK* get_http_auth_credentials)(
      struct _cef_data_base_t* self,
      const cef_string_t* host,
      const cef_string_t* realm,
      cef_string_list_t username_password);

  ///
  // gets whether the instance holds the specified permissions for the specified
  // source.
  ///
  int(CEF_CALLBACK* exist_permission_by_origin)(struct _cef_data_base_t* self,
                                                const cef_string_t* origin,
                                                int type);

  ///
  // get specifies permission type result by origin.
  ///
  int(CEF_CALLBACK* get_permission_result_by_origin)(
      struct _cef_data_base_t* self,
      const cef_string_t* origin,
      int type,
      int* result);

  ///
  // set specifies permission type by origin.
  ///
  void(CEF_CALLBACK* set_permission_by_origin)(struct _cef_data_base_t* self,
                                               const cef_string_t* origin,
                                               int type,
                                               int result);

  ///
  // delete specifies permission type by origin.
  ///
  void(CEF_CALLBACK* clear_permission_by_origin)(struct _cef_data_base_t* self,
                                                 const cef_string_t* origin,
                                                 int type);

  ///
  // delete all specifies permission type.
  ///
  void(CEF_CALLBACK* clear_all_permission)(struct _cef_data_base_t* self,
                                           int type);

  ///
  // obtains all origins of a specified permission type.
  ///
  void(CEF_CALLBACK* get_origins_by_permission)(struct _cef_data_base_t* self,
                                                int type,
                                                cef_string_list_t origins);
} cef_data_base_t;

///
// Returns the global data base instance.
///
CEF_EXPORT cef_data_base_t* cef_data_base_get_global();

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_CEF_DATA_BASE_CAPI_H_
