// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=d33bcb9994f8d50fd73e593c73f1d90e2655bcab$
//

#ifndef CEF_INCLUDE_CAPI_VIEWS_CEF_SCROLL_VIEW_CAPI_VERSIONS_H_
#define CEF_INCLUDE_CAPI_VIEWS_CEF_SCROLL_VIEW_CAPI_VERSIONS_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/views/cef_view_capi_versions.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _cef_scroll_view_0_t {
  cef_view_0_t base;
  void (CEF_CALLBACK *set_content_view)(struct _cef_scroll_view_0_t* self, struct _cef_view_0_t* view);
  struct _cef_view_0_t* (CEF_CALLBACK *get_content_view)(struct _cef_scroll_view_0_t* self);
  cef_rect_t (CEF_CALLBACK *get_visible_content_rect)(struct _cef_scroll_view_0_t* self);
  int (CEF_CALLBACK *has_horizontal_scrollbar)(struct _cef_scroll_view_0_t* self);
  int (CEF_CALLBACK *get_horizontal_scrollbar_height)(struct _cef_scroll_view_0_t* self);
  int (CEF_CALLBACK *has_vertical_scrollbar)(struct _cef_scroll_view_0_t* self);
  int (CEF_CALLBACK *get_vertical_scrollbar_width)(struct _cef_scroll_view_0_t* self);
} cef_scroll_view_0_t;

CEF_EXPORT cef_scroll_view_0_t* cef_scroll_view_create(struct _cef_view_delegate_0_t* delegate);

#ifdef __cplusplus
}
#endif

#endif  // CEF_INCLUDE_CAPI_VIEWS_CEF_SCROLL_VIEW_CAPI_VERSIONS_H_
