// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=ce96b6db0db161cf73bfca38e418f263043275b8$
//

#include "libcef_dll/ctocpp/access_request_ctocpp.h"

#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") CefString CefAccessRequestCToCpp::Origin() {
  shutdown_checker::AssertNotShutdown();

  cef_access_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, origin)) {
    return CefString();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_string_userfree_t _retval = _struct->origin(_struct);

  // Return type: string
  CefString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

NO_SANITIZE("cfi-icall") int CefAccessRequestCToCpp::ResourceAcessId() {
  shutdown_checker::AssertNotShutdown();

  cef_access_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, resource_acess_id)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->resource_acess_id(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void CefAccessRequestCToCpp::ReportRequestResult(bool allowed) {
  shutdown_checker::AssertNotShutdown();

  cef_access_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, report_request_result)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->report_request_result(_struct, allowed);
}

// CONSTRUCTOR - Do not edit by hand.

CefAccessRequestCToCpp::CefAccessRequestCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefAccessRequestCToCpp::~CefAccessRequestCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_access_request_t*
CefCToCppRefCounted<CefAccessRequestCToCpp,
                    CefAccessRequest,
                    cef_access_request_t>::UnwrapDerived(CefWrapperType type,
                                                         CefAccessRequest* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefAccessRequestCToCpp,
                                   CefAccessRequest,
                                   cef_access_request_t>::kWrapperType =
    WT_ACCESS_REQUEST;
