// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=2ac4abefe4e706d1710d2066f37bfc0fca3bd020$
//

#include "libcef_dll/ctocpp/ads_block_manager_ctocpp.h"

#include "libcef_dll/cpptoc/completion_callback_cpptoc.h"
#include "libcef_dll/transfer_util.h"

// STATIC METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
CefRefPtr<CefAdsBlockManager> CefAdsBlockManager::GetGlobalAdsBlockManager(
    CefRefPtr<CefCompletionCallback> callback) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: callback

  // Execute
  cef_ads_block_manager_t* _retval = cef_ads_block_manager_get_global(
      CefCompletionCallbackCppToC::Wrap(callback));

  // Return type: refptr_same
  return CefAdsBlockManagerCToCpp::Wrap(_retval);
}

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefAdsBlockManagerCToCpp::SetAdsBlockRules(const CefString& rulesFile,
                                                bool replace) {
  cef_ads_block_manager_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, set_ads_block_rules)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: rulesFile; type: string_byref_const
  DCHECK(!rulesFile.empty());
  if (rulesFile.empty()) {
    return;
  }

  // Execute
  _struct->set_ads_block_rules(_struct, rulesFile.GetStruct(), replace);
}

NO_SANITIZE("cfi-icall")
void CefAdsBlockManagerCToCpp::AddAdsBlockDisallowedList(
    const std::vector<CefString>& domainSuffixes) {
  cef_ads_block_manager_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, add_ads_block_disallowed_list)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: domainSuffixes; type: string_vec_byref_const
  cef_string_list_t domainSuffixesList = cef_string_list_alloc();
  DCHECK(domainSuffixesList);
  if (domainSuffixesList) {
    transfer_string_list_contents(domainSuffixes, domainSuffixesList);
  }

  // Execute
  _struct->add_ads_block_disallowed_list(_struct, domainSuffixesList);

  // Restore param:domainSuffixes; type: string_vec_byref_const
  if (domainSuffixesList) {
    cef_string_list_free(domainSuffixesList);
  }
}

NO_SANITIZE("cfi-icall")
void CefAdsBlockManagerCToCpp::RemoveAdsBlockDisallowedList(
    const std::vector<CefString>& domainSuffixes) {
  cef_ads_block_manager_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, remove_ads_block_disallowed_list)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: domainSuffixes; type: string_vec_byref_const
  cef_string_list_t domainSuffixesList = cef_string_list_alloc();
  DCHECK(domainSuffixesList);
  if (domainSuffixesList) {
    transfer_string_list_contents(domainSuffixes, domainSuffixesList);
  }

  // Execute
  _struct->remove_ads_block_disallowed_list(_struct, domainSuffixesList);

  // Restore param:domainSuffixes; type: string_vec_byref_const
  if (domainSuffixesList) {
    cef_string_list_free(domainSuffixesList);
  }
}

NO_SANITIZE("cfi-icall")
void CefAdsBlockManagerCToCpp::ClearAdsBlockDisallowedList() {
  cef_ads_block_manager_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, clear_ads_block_disallowed_list)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->clear_ads_block_disallowed_list(_struct);
}

NO_SANITIZE("cfi-icall")
void CefAdsBlockManagerCToCpp::AddAdsBlockAllowedList(
    const std::vector<CefString>& domainSuffixes) {
  cef_ads_block_manager_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, add_ads_block_allowed_list)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: domainSuffixes; type: string_vec_byref_const
  cef_string_list_t domainSuffixesList = cef_string_list_alloc();
  DCHECK(domainSuffixesList);
  if (domainSuffixesList) {
    transfer_string_list_contents(domainSuffixes, domainSuffixesList);
  }

  // Execute
  _struct->add_ads_block_allowed_list(_struct, domainSuffixesList);

  // Restore param:domainSuffixes; type: string_vec_byref_const
  if (domainSuffixesList) {
    cef_string_list_free(domainSuffixesList);
  }
}

NO_SANITIZE("cfi-icall")
void CefAdsBlockManagerCToCpp::RemoveAdsBlockAllowedList(
    const std::vector<CefString>& domainSuffixes) {
  cef_ads_block_manager_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, remove_ads_block_allowed_list)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: domainSuffixes; type: string_vec_byref_const
  cef_string_list_t domainSuffixesList = cef_string_list_alloc();
  DCHECK(domainSuffixesList);
  if (domainSuffixesList) {
    transfer_string_list_contents(domainSuffixes, domainSuffixesList);
  }

  // Execute
  _struct->remove_ads_block_allowed_list(_struct, domainSuffixesList);

  // Restore param:domainSuffixes; type: string_vec_byref_const
  if (domainSuffixesList) {
    cef_string_list_free(domainSuffixesList);
  }
}

NO_SANITIZE("cfi-icall")
void CefAdsBlockManagerCToCpp::ClearAdsBlockAllowedList() {
  cef_ads_block_manager_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, clear_ads_block_allowed_list)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->clear_ads_block_allowed_list(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

CefAdsBlockManagerCToCpp::CefAdsBlockManagerCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefAdsBlockManagerCToCpp::~CefAdsBlockManagerCToCpp() {}

template <>
cef_ads_block_manager_t* CefCToCppRefCounted<
    CefAdsBlockManagerCToCpp,
    CefAdsBlockManager,
    cef_ads_block_manager_t>::UnwrapDerived(CefWrapperType type,
                                            CefAdsBlockManager* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefAdsBlockManagerCToCpp,
                                   CefAdsBlockManager,
                                   cef_ads_block_manager_t>::kWrapperType =
    WT_ADS_BLOCK_MANAGER;
