// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b19528ad423692cfb0dcd66203ce51f4529b6782$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_BROWSER_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_BROWSER_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_browser_capi.h"
#include "include/capi/cef_client_capi.h"
#include "include/cef_browser.h"
#include "include/cef_client.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"
#include <vector>

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefBrowserCToCpp
    : public CefCToCppRefCounted<CefBrowserCToCpp, CefBrowser, cef_browser_t> {
public:
  CefBrowserCToCpp();
  virtual ~CefBrowserCToCpp();

  // CefBrowser methods.
  bool IsValid() override;
  CefRefPtr<CefBrowserHost> GetHost() override;
  bool CanGoBack() override;
  void GoBack() override;
  bool CanGoForward() override;
  void GoForward() override;
  bool IsLoading() override;
  void Reload() override;
  void ReloadIgnoreCache() override;
  void StopLoad() override;
  int GetIdentifier() override;
  bool IsSame(CefRefPtr<CefBrowser> that) override;
  bool IsPopup() override;
  bool HasDocument() override;
  CefRefPtr<CefFrame> GetMainFrame() override;
  CefRefPtr<CefFrame> GetFocusedFrame() override;
  CefRefPtr<CefFrame> GetFrame(int64 identifier) override;
  CefRefPtr<CefFrame> GetFrame(const CefString &name) override;
  size_t GetFrameCount() override;
  void GetFrameIdentifiers(std::vector<int64> &identifiers) override;
  void GetFrameNames(std::vector<CefString> &names) override;
  CefRefPtr<CefBrowserPermissionRequestDelegate>
  GetPermissionRequestDelegate() override;
  CefRefPtr<CefGeolocationAcess> GetGeolocationPermissions() override;
  bool CanGoBackOrForward(int num_steps) override;
  void GoBackOrForward(int num_steps) override;
  void DeleteHistory() override;
  void SelectAndCopy() override;
  bool ShouldShowFreeCopy() override;
  void PasswordSuggestionSelected(int list_index) override;
  void UpdateBrowserControlsState(int constraints, int current,
                                  bool animate) override;
  void UpdateBrowserControlsHeight(int height, bool animate) override;
  void PrefetchPage(CefString &url, CefString &additionalHttpHeaders) override;
  void ReloadOriginalUrl() override;
  bool CanStoreWebArchive() override;
  void SetBrowserUserAgentString(const CefString &user_agent) override;
  bool ShouldShowLoadingUI() override;
  void SetForceEnableZoom(bool forceEnableZoom) override;
  bool GetForceEnableZoom() override;
  int GetNWebId() override;
  void SetEnableBlankTargetPopupIntercept(bool enableBlankTargetPopup) override;
  bool GetSavePasswordAutomatically() override;
  void SetSavePasswordAutomatically(bool enable) override;
  void SaveOrUpdatePassword(bool is_update) override;
  bool GetSavePassword() override;
  void SetSavePassword(bool enable) override;
  int GetSecurityLevel() override;
  void EnableSafeBrowsing(bool enable) override;
  bool IsSafeBrowsingEnabled() override;
  void EnableIntelligentTrackingPrevention(bool enable) override;
  bool IsIntelligentTrackingPreventionEnabled() override;
};

#endif // CEF_LIBCEF_DLL_CTOCPP_BROWSER_CTOCPP_H_
