// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=cdbc417c9eae19e3955d8e4ca88064ac39e433c6$
//

#include "libcef_dll/ctocpp/browser_ctocpp.h"
#include "libcef_dll/ctocpp/browser_host_ctocpp.h"
#include "libcef_dll/ctocpp/browser_permission_request_delegate_ctocpp.h"
#include "libcef_dll/ctocpp/frame_ctocpp.h"
#include "libcef_dll/ctocpp/geolocation_acess_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"
#include "libcef_dll/transfer_util.h"
#include <algorithm>

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::IsValid() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_valid)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_valid(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") CefRefPtr<CefBrowserHost> CefBrowserCToCpp::GetHost() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_host)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_browser_host_t *_retval = _struct->get_host(_struct);

  // Return type: refptr_same
  return CefBrowserHostCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::CanGoBack() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, can_go_back)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->can_go_back(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::GoBack() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, go_back)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->go_back(_struct);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::CanGoForward() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, can_go_forward)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->can_go_forward(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::GoForward() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, go_forward)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->go_forward(_struct);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::IsLoading() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_loading)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_loading(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::Reload() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, reload)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->reload(_struct);
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::ReloadIgnoreCache() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, reload_ignore_cache)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->reload_ignore_cache(_struct);
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::StopLoad() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, stop_load)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->stop_load(_struct);
}

NO_SANITIZE("cfi-icall") int CefBrowserCToCpp::GetIdentifier() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_identifier)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_identifier(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
bool CefBrowserCToCpp::IsSame(CefRefPtr<CefBrowser> that) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_same)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: that; type: refptr_same
  DCHECK(that.get());
  if (!that.get()) {
    return false;
  }

  // Execute
  int _retval = _struct->is_same(_struct, CefBrowserCToCpp::Unwrap(that));

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::IsPopup() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_popup)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_popup(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::HasDocument() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, has_document)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->has_document(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") CefRefPtr<CefFrame> CefBrowserCToCpp::GetMainFrame() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_main_frame)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_frame_t *_retval = _struct->get_main_frame(_struct);

  // Return type: refptr_same
  return CefFrameCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
CefRefPtr<CefFrame> CefBrowserCToCpp::GetFocusedFrame() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_focused_frame)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_frame_t *_retval = _struct->get_focused_frame(_struct);

  // Return type: refptr_same
  return CefFrameCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
CefRefPtr<CefFrame> CefBrowserCToCpp::GetFrame(int64 identifier) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_frame_byident)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_frame_t *_retval = _struct->get_frame_byident(_struct, identifier);

  // Return type: refptr_same
  return CefFrameCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
CefRefPtr<CefFrame> CefBrowserCToCpp::GetFrame(const CefString &name) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_frame)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: name

  // Execute
  cef_frame_t *_retval = _struct->get_frame(_struct, name.GetStruct());

  // Return type: refptr_same
  return CefFrameCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") size_t CefBrowserCToCpp::GetFrameCount() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_frame_count)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  size_t _retval = _struct->get_frame_count(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::GetFrameIdentifiers(std::vector<int64> &identifiers) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_frame_identifiers)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: identifiers; type: simple_vec_byref
  size_t identifiersSize = identifiers.size();
  size_t identifiersCount = std::max(GetFrameCount(), identifiersSize);
  int64 *identifiersList = NULL;
  if (identifiersCount > 0) {
    identifiersList = new int64[identifiersCount];
    DCHECK(identifiersList);
    if (identifiersList) {
      memset(identifiersList, 0, sizeof(int64) * identifiersCount);
    }
    if (identifiersList && identifiersSize > 0) {
      for (size_t i = 0; i < identifiersSize; ++i) {
        identifiersList[i] = identifiers[i];
      }
    }
  }

  // Execute
  _struct->get_frame_identifiers(_struct, &identifiersCount, identifiersList);

  // Restore param:identifiers; type: simple_vec_byref
  identifiers.clear();
  if (identifiersCount > 0 && identifiersList) {
    for (size_t i = 0; i < identifiersCount; ++i) {
      identifiers.push_back(identifiersList[i]);
    }
    delete[] identifiersList;
  }
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::GetFrameNames(std::vector<CefString> &names) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_frame_names)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: names; type: string_vec_byref
  cef_string_list_t namesList = cef_string_list_alloc();
  DCHECK(namesList);
  if (namesList) {
    transfer_string_list_contents(names, namesList);
  }

  // Execute
  _struct->get_frame_names(_struct, namesList);

  // Restore param:names; type: string_vec_byref
  if (namesList) {
    names.clear();
    transfer_string_list_contents(namesList, names);
    cef_string_list_free(namesList);
  }
}

NO_SANITIZE("cfi-icall")
CefRefPtr<CefBrowserPermissionRequestDelegate> CefBrowserCToCpp::
    GetPermissionRequestDelegate() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_permission_request_delegate)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_browser_permission_request_delegate_t *_retval =
      _struct->get_permission_request_delegate(_struct);

  // Return type: refptr_same
  return CefBrowserPermissionRequestDelegateCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
CefRefPtr<CefGeolocationAcess> CefBrowserCToCpp::GetGeolocationPermissions() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_geolocation_permissions)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_geolocation_acess_t *_retval =
      _struct->get_geolocation_permissions(_struct);

  // Return type: refptr_same
  return CefGeolocationAcessCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
bool CefBrowserCToCpp::CanGoBackOrForward(int num_steps) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, can_go_back_or_forward)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->can_go_back_or_forward(_struct, num_steps);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::GoBackOrForward(int num_steps) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, go_back_or_forward)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->go_back_or_forward(_struct, num_steps);
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::DeleteHistory() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, delete_history)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->delete_history(_struct);
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::SelectAndCopy() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, select_and_copy)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->select_and_copy(_struct);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::ShouldShowFreeCopy() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, should_show_free_copy)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->should_show_free_copy(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::PasswordSuggestionSelected(int list_index) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, password_suggestion_selected)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->password_suggestion_selected(_struct, list_index);
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::UpdateBrowserControlsState(int constraints, int current,
                                                  bool animate) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, update_browser_controls_state)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->update_browser_controls_state(_struct, constraints, current,
                                         animate);
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::UpdateBrowserControlsHeight(int height, bool animate) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, update_browser_controls_height)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->update_browser_controls_height(_struct, height, animate);
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::PrefetchPage(CefString &url,
                                    CefString &additionalHttpHeaders) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, prefetch_page)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->prefetch_page(_struct, url.GetWritableStruct(),
                         additionalHttpHeaders.GetWritableStruct());
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::ReloadOriginalUrl() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, reload_original_url)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->reload_original_url(_struct);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::CanStoreWebArchive() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, can_store_web_archive)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->can_store_web_archive(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::SetBrowserUserAgentString(const CefString &user_agent) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, set_browser_user_agent_string)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: user_agent; type: string_byref_const
  DCHECK(!user_agent.empty());
  if (user_agent.empty()) {
    return;
  }

  // Execute
  _struct->set_browser_user_agent_string(_struct, user_agent.GetStruct());
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::ShouldShowLoadingUI() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, should_show_loading_ui)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->should_show_loading_ui(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::SetForceEnableZoom(bool forceEnableZoom) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, set_force_enable_zoom)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_force_enable_zoom(_struct, forceEnableZoom);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::GetForceEnableZoom() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_force_enable_zoom)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_force_enable_zoom(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") int CefBrowserCToCpp::GetNWebId() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_nweb_id)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_nweb_id(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::SetEnableBlankTargetPopupIntercept(
    bool enableBlankTargetPopup) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, set_enable_blank_target_popup_intercept)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_enable_blank_target_popup_intercept(_struct,
                                                   enableBlankTargetPopup);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::GetSavePasswordAutomatically() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_save_password_automatically)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_save_password_automatically(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::SetSavePasswordAutomatically(bool enable) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, set_save_password_automatically)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_save_password_automatically(_struct, enable);
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::SaveOrUpdatePassword(bool is_update) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, save_or_update_password)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->save_or_update_password(_struct, is_update);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::GetSavePassword() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_save_password)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_save_password(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void CefBrowserCToCpp::SetSavePassword(bool enable) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, set_save_password)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_save_password(_struct, enable);
}

NO_SANITIZE("cfi-icall") int CefBrowserCToCpp::GetSecurityLevel() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_security_level)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_security_level(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::EnableSafeBrowsing(bool enable) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, enable_safe_browsing)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->enable_safe_browsing(_struct, enable);
}

NO_SANITIZE("cfi-icall") bool CefBrowserCToCpp::IsSafeBrowsingEnabled() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_safe_browsing_enabled)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_safe_browsing_enabled(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
void CefBrowserCToCpp::EnableIntelligentTrackingPrevention(bool enable) {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, enable_intelligent_tracking_prevention)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->enable_intelligent_tracking_prevention(_struct, enable);
}

NO_SANITIZE("cfi-icall")
bool CefBrowserCToCpp::IsIntelligentTrackingPreventionEnabled() {
  shutdown_checker::AssertNotShutdown();

  cef_browser_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_intelligent_tracking_prevention_enabled)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_intelligent_tracking_prevention_enabled(_struct);

  // Return type: bool
  return _retval ? true : false;
}

// CONSTRUCTOR - Do not edit by hand.

CefBrowserCToCpp::CefBrowserCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefBrowserCToCpp::~CefBrowserCToCpp() { shutdown_checker::AssertNotShutdown(); }

template <>
cef_browser_t *
CefCToCppRefCounted<CefBrowserCToCpp, CefBrowser, cef_browser_t>::UnwrapDerived(
    CefWrapperType type, CefBrowser *c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefBrowserCToCpp, CefBrowser,
                                   cef_browser_t>::kWrapperType = WT_BROWSER;
