// Copyright (c) 2022 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c9c5f759ffc22b4c39e35c6273d17966ec357b35$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_BROWSER_PERMISSION_REQUEST_DELEGATE_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_BROWSER_PERMISSION_REQUEST_DELEGATE_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_permission_request_capi.h"
#include "include/cef_permission_request.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefBrowserPermissionRequestDelegateCToCpp
    : public CefCToCppRefCounted<CefBrowserPermissionRequestDelegateCToCpp,
                                 CefBrowserPermissionRequestDelegate,
                                 cef_browser_permission_request_delegate_t> {
public:
  CefBrowserPermissionRequestDelegateCToCpp();
  virtual ~CefBrowserPermissionRequestDelegateCToCpp();

  // CefBrowserPermissionRequestDelegate methods.
  void AskGeolocationPermission(const CefString &origin,
                                cef_permission_callback_t callback) override;
  void AbortAskGeolocationPermission(const CefString &origin) override;
  void AskProtectedMediaIdentifierPermission(
      const CefString &origin, cef_permission_callback_t callback) override;
  void
  AbortAskProtectedMediaIdentifierPermission(const CefString &origin) override;
  void AskMIDISysexPermission(const CefString &origin,
                              cef_permission_callback_t callback) override;
  void AbortAskMIDISysexPermission(const CefString &origin) override;
  void NotifyGeolocationPermission(bool value,
                                   const CefString &origin) override;
};

#endif // CEF_LIBCEF_DLL_CTOCPP_BROWSER_PERMISSION_REQUEST_DELEGATE_CTOCPP_H_
