// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b662198b471e532f190957fb7f7f251fbf02bb19$
//

#include "libcef_dll/ctocpp/cache_options_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
cef_string_map_t CefCacheOptionsCToCpp::GetResponseHeaders() {
  shutdown_checker::AssertNotShutdown();

  cef_cache_options_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_response_headers)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_string_map_t _retval = _struct->get_response_headers(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") bool CefCacheOptionsCToCpp::IsModule() {
  shutdown_checker::AssertNotShutdown();

  cef_cache_options_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_module)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_module(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool CefCacheOptionsCToCpp::IsTopLevel() {
  shutdown_checker::AssertNotShutdown();

  cef_cache_options_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_top_level)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_top_level(_struct);

  // Return type: bool
  return _retval ? true : false;
}

// CONSTRUCTOR - Do not edit by hand.

CefCacheOptionsCToCpp::CefCacheOptionsCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefCacheOptionsCToCpp::~CefCacheOptionsCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_cache_options_t *
CefCToCppRefCounted<CefCacheOptionsCToCpp, CefCacheOptions,
                    cef_cache_options_t>::UnwrapDerived(CefWrapperType type,
                                                        CefCacheOptions *c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefCacheOptionsCToCpp, CefCacheOptions,
                                   cef_cache_options_t>::kWrapperType =
    WT_CACHE_OPTIONS;
