// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=45dbc17af578d48e8690b6590059098436694b09$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_COLOR_CHOOSER_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_COLOR_CHOOSER_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_dialog_handler_capi.h"
#include "include/cef_dialog_handler.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefColorChooserCallbackCToCpp
    : public CefCToCppRefCounted<CefColorChooserCallbackCToCpp,
                                 CefColorChooserCallback,
                                 cef_color_chooser_callback_t> {
 public:
  CefColorChooserCallbackCToCpp();
  virtual ~CefColorChooserCallbackCToCpp();

  // CefColorChooserCallback methods.
  void Continue(uint32_t color) override;
  void Cancel() override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_COLOR_CHOOSER_CALLBACK_CTOCPP_H_
