// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a4a34d94447f7d69b83283f1f41f701a204a4b69$
//

#include "libcef_dll/ctocpp/color_chooser_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefColorChooserCallbackCToCpp::Continue(uint32_t color) {
  shutdown_checker::AssertNotShutdown();

  cef_color_chooser_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cont)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cont(_struct, color);
}

NO_SANITIZE("cfi-icall") void CefColorChooserCallbackCToCpp::Cancel() {
  shutdown_checker::AssertNotShutdown();

  cef_color_chooser_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cancel)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cancel(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

CefColorChooserCallbackCToCpp::CefColorChooserCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefColorChooserCallbackCToCpp::~CefColorChooserCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_color_chooser_callback_t* CefCToCppRefCounted<
    CefColorChooserCallbackCToCpp,
    CefColorChooserCallback,
    cef_color_chooser_callback_t>::UnwrapDerived(CefWrapperType type,
                                                 CefColorChooserCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefColorChooserCallbackCToCpp,
                                   CefColorChooserCallback,
                                   cef_color_chooser_callback_t>::kWrapperType =
    WT_COLOR_CHOOSER_CALLBACK;
