// Copyright (c) 2022 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7b5c7ec8ac08f9547744baa38e840cf35a3e7a25$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_DATA_BASE_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_DATA_BASE_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include <vector>
#include "include/capi/cef_data_base_capi.h"
#include "include/cef_data_base.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefDataBaseCToCpp : public CefCToCppRefCounted<CefDataBaseCToCpp,
                                                     CefDataBase,
                                                     cef_data_base_t> {
 public:
  CefDataBaseCToCpp();
  virtual ~CefDataBaseCToCpp();

  // CefDataBase methods.
  void DeleteHttpAuthCredentials() override;
  bool ExistHttpAuthCredentials() override;
  void SaveHttpAuthCredentials(const CefString& host,
                               const CefString& realm,
                               const CefString& username,
                               const char* password) override;
  void GetHttpAuthCredentials(
      const CefString& host,
      const CefString& realm,
      std::vector<CefString>& username_password) override;
  bool ExistPermissionByOrigin(const CefString& origin, int type) override;
  bool GetPermissionResultByOrigin(const CefString& origin,
                                   int type,
                                   bool& result) override;
  void SetPermissionByOrigin(const CefString& origin,
                             int type,
                             bool result) override;
  void ClearPermissionByOrigin(const CefString& origin, int type) override;
  void ClearAllPermission(int type) override;
  void GetOriginsByPermission(int type,
                              std::vector<CefString>& origins) override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_DATA_BASE_CTOCPP_H_
