// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=55a1bec5bd5930054412e58c21d65862c7d8c5d4$
//

#include "include/cef_api_hash.h"
#include "libcef_dll/ctocpp/delete_cookies_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"


// VIRTUAL METHODS FOR VERSION 0 - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefDeleteCookiesCallback_0_CToCpp::OnComplete(int num_deleted) {
  shutdown_checker::AssertNotShutdown();

  auto* _struct = GetStruct();
  if (!_struct->on_complete) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->on_complete(_struct,
      num_deleted);
}

// CONSTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefDeleteCookiesCallback_0_CToCpp::CefDeleteCookiesCallback_0_CToCpp() {
  const int version = cef_api_version();
  LOG_IF(FATAL, version < 0) << __func__ << " called with invalid version " << version;
}

// DESTRUCTOR FOR VERSION 0 - Do not edit by hand.

CefDeleteCookiesCallback_0_CToCpp::~CefDeleteCookiesCallback_0_CToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template<> cef_delete_cookies_callback_0_t* CefCToCppRefCounted<CefDeleteCookiesCallback_0_CToCpp, CefDeleteCookiesCallback, cef_delete_cookies_callback_0_t>::UnwrapDerived(CefWrapperType type, CefDeleteCookiesCallback* c) {
  NOTREACHED() << __func__ << " called with unexpected class type " << type;
}

template<> CefWrapperType CefCToCppRefCounted<CefDeleteCookiesCallback_0_CToCpp, CefDeleteCookiesCallback, cef_delete_cookies_callback_0_t>::kWrapperType = WT_DELETE_COOKIES_CALLBACK;


