// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=55dba640c3e02667053652c612e6e3c1c56aeed8$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_GEOLOCATION_ACESS_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_GEOLOCATION_ACESS_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_permission_request_capi.h"
#include "include/cef_permission_request.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefGeolocationAcessCToCpp
    : public CefCToCppRefCounted<CefGeolocationAcessCToCpp,
                                 CefGeolocationAcess,
                                 cef_geolocation_acess_t> {
 public:
  CefGeolocationAcessCToCpp();
  virtual ~CefGeolocationAcessCToCpp();

  // CefGeolocationAcess methods.
  bool ContainOrigin(const CefString& origin) override;
  bool IsOriginAccessEnabled(const CefString& origin) override;
  void Enabled(const CefString& origin, bool incognito) override;
  void Disabled(const CefString& origin, bool incognito) override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_GEOLOCATION_ACESS_CTOCPP_H_
