// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=de54c97c2f6e47cb0b8114cf99507065ddab6719$
//

#include "libcef_dll/ctocpp/gesture_event_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefGestureEventCallbackCToCpp::ContinueTask(bool result, bool stopPropagation) {
  shutdown_checker::AssertNotShutdown();

  cef_gesture_event_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, continue_task)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->continue_task(_struct, result, stopPropagation);
}

// CONSTRUCTOR - Do not edit by hand.

CefGestureEventCallbackCToCpp::CefGestureEventCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefGestureEventCallbackCToCpp::~CefGestureEventCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_gesture_event_callback_t* CefCToCppRefCounted<
    CefGestureEventCallbackCToCpp,
    CefGestureEventCallback,
    cef_gesture_event_callback_t>::UnwrapDerived(CefWrapperType type,
                                                 CefGestureEventCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefGestureEventCallbackCToCpp,
                                   CefGestureEventCallback,
                                   cef_gesture_event_callback_t>::kWrapperType =
    WT_GESTURE_EVENT_CALLBACK;
