// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=502b4047783bf803d20962fea229bac108607ada$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_GET_SAVED_PASSWORDS_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_GET_SAVED_PASSWORDS_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include <vector>
#include "include/capi/cef_web_storage_capi.h"
#include "include/cef_web_storage.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class CefGetSavedPasswordsCallbackCToCpp
    : public CefCToCppRefCounted<CefGetSavedPasswordsCallbackCToCpp,
                                 CefGetSavedPasswordsCallback,
                                 cef_get_saved_passwords_callback_t> {
 public:
  CefGetSavedPasswordsCallbackCToCpp();
  virtual ~CefGetSavedPasswordsCallbackCToCpp();

  // CefGetSavedPasswordsCallback methods.
  void OnComplete(const std::vector<CefString>& url,
                  const std::vector<CefString>& username) override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_GET_SAVED_PASSWORDS_CALLBACK_CTOCPP_H_
