// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=04ea484d6a097c4d8d55af574ebb5a44ad1daa15$
//

#include "libcef_dll/ctocpp/info_bar_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefInfoBarCallbackCToCpp::Allow(bool allow) {
  shutdown_checker::AssertNotShutdown();

  cef_info_bar_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, allow)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->allow(_struct, allow);
}

// CONSTRUCTOR - Do not edit by hand.

CefInfoBarCallbackCToCpp::CefInfoBarCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefInfoBarCallbackCToCpp::~CefInfoBarCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_info_bar_callback_t* CefCToCppRefCounted<
    CefInfoBarCallbackCToCpp,
    CefInfoBarCallback,
    cef_info_bar_callback_t>::UnwrapDerived(CefWrapperType type,
                                            CefInfoBarCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefInfoBarCallbackCToCpp,
                                   CefInfoBarCallback,
                                   cef_info_bar_callback_t>::kWrapperType =
    WT_INFO_BAR_CALLBACK;
