// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=d90af3290c277c74424fe928c26c23df933d331e$
//

#include "libcef_dll/ctocpp/intercept_callback_ctocpp.h"

#include "libcef_dll/cpptoc/resource_handler_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefInterceptCallbackCToCpp::ContinueLoad(
    CefRefPtr<CefResourceHandler> resource_handler) {
  shutdown_checker::AssertNotShutdown();

  cef_intercept_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cont)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: resource_handler; type: refptr_diff
  DCHECK(resource_handler.get());
  if (!resource_handler.get()) {
    return;
  }

  // Execute
  _struct->cont(_struct, CefResourceHandlerCppToC::Wrap(resource_handler));
}

// CONSTRUCTOR - Do not edit by hand.

CefInterceptCallbackCToCpp::CefInterceptCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefInterceptCallbackCToCpp::~CefInterceptCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_intercept_callback_t* CefCToCppRefCounted<
    CefInterceptCallbackCToCpp,
    CefInterceptCallback,
    cef_intercept_callback_t>::UnwrapDerived(CefWrapperType type,
                                             CefInterceptCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefInterceptCallbackCToCpp,
                                   CefInterceptCallback,
                                   cef_intercept_callback_t>::kWrapperType =
    WT_INTERCEPT_CALLBACK;
