// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=75be9f9b1aafa8d158819a9803ba8c352f579f44$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_LOAD_COMMITTED_DETAILS_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_LOAD_COMMITTED_DETAILS_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_load_committed_details_capi.h"
#include "include/cef_load_committed_details.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefLoadCommittedDetailsCToCpp
    : public CefCToCppRefCounted<CefLoadCommittedDetailsCToCpp,
                                 CefLoadCommittedDetails,
                                 cef_load_committed_details_t> {
 public:
  CefLoadCommittedDetailsCToCpp();
  virtual ~CefLoadCommittedDetailsCToCpp();

  // CefLoadCommittedDetails methods.
  bool IsMainFrame() override;
  bool IsSameDocument() override;
  bool DidReplaceEntry() override;
  NavigationType GetNavigationType() override;
  CefString GetCurrentURL() override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_LOAD_COMMITTED_DETAILS_CTOCPP_H_
