// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=fd772c0574bb9267855186aec900946131ee33aa$
//

#include "libcef_dll/ctocpp/media_handler_ctocpp.h"
#include "libcef_dll/cpptoc/browser_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefMediaHandlerCToCpp::OnAudioStateChanged(CefRefPtr<CefBrowser> browser,
                                                bool audible) {
  shutdown_checker::AssertNotShutdown();

  cef_media_handler_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_audio_state_changed)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: browser; type: refptr_diff
  DCHECK(browser.get());
  if (!browser.get()) {
    return;
  }

  // Execute
  _struct->on_audio_state_changed(_struct, CefBrowserCppToC::Wrap(browser),
                                  audible);
}

NO_SANITIZE("cfi-icall")
void CefMediaHandlerCToCpp::OnMediaStateChanged(CefRefPtr<CefBrowser> browser,
                                                MediaType type,
                                                MediaPlayingState state) {
  shutdown_checker::AssertNotShutdown();

  cef_media_handler_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_media_state_changed)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: browser; type: refptr_diff
  DCHECK(browser.get());
  if (!browser.get()) {
    return;
  }

  // Execute
  _struct->on_media_state_changed(_struct, CefBrowserCppToC::Wrap(browser),
                                  type, state);
}

// CONSTRUCTOR - Do not edit by hand.

CefMediaHandlerCToCpp::CefMediaHandlerCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefMediaHandlerCToCpp::~CefMediaHandlerCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_media_handler_t*
CefCToCppRefCounted<CefMediaHandlerCToCpp,
                    CefMediaHandler,
                    cef_media_handler_t>::UnwrapDerived(CefWrapperType type,
                                                        CefMediaHandler* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefMediaHandlerCToCpp,
                                   CefMediaHandler,
                                   cef_media_handler_t>::kWrapperType =
    WT_MEDIA_HANDLER;
