// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=97d3c36058119ebe4fbb2d188c91ce8fd1d85c94$
//

#include "libcef_dll/ctocpp/open_app_link_callback_ctocpp.h"

#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefOpenAppLinkCallbackCToCpp::Continue() {
  shutdown_checker::AssertNotShutdown();

  cef_open_app_link_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cont)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cont(_struct);
}

NO_SANITIZE("cfi-icall") void CefOpenAppLinkCallbackCToCpp::Cancel() {
  shutdown_checker::AssertNotShutdown();

  cef_open_app_link_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cancel)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cancel(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

CefOpenAppLinkCallbackCToCpp::CefOpenAppLinkCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefOpenAppLinkCallbackCToCpp::~CefOpenAppLinkCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_open_app_link_callback_t* CefCToCppRefCounted<
    CefOpenAppLinkCallbackCToCpp,
    CefOpenAppLinkCallback,
    cef_open_app_link_callback_t>::UnwrapDerived(CefWrapperType type,
                                                 CefOpenAppLinkCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefOpenAppLinkCallbackCToCpp,
                                   CefOpenAppLinkCallback,
                                   cef_open_app_link_callback_t>::kWrapperType =
    WT_OPEN_APP_LINK_CALLBACK;
