// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=29af672c7851a15b1940bdbf0724420a5925c477$
//

#include "libcef_dll/ctocpp/pdf_value_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefPdfValueCallbackCToCpp::OnReceiveValue(const char* value,
                                               const long size) {
  shutdown_checker::AssertNotShutdown();

  cef_pdf_value_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_receive_value)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: value; type: simple_byaddr
  DCHECK(value);
  if (!value) {
    return;
  }

  // Execute
  _struct->on_receive_value(_struct, value, size);
}

// CONSTRUCTOR - Do not edit by hand.

CefPdfValueCallbackCToCpp::CefPdfValueCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefPdfValueCallbackCToCpp::~CefPdfValueCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_pdf_value_callback_t* CefCToCppRefCounted<
    CefPdfValueCallbackCToCpp,
    CefPdfValueCallback,
    cef_pdf_value_callback_t>::UnwrapDerived(CefWrapperType type,
                                             CefPdfValueCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefPdfValueCallbackCToCpp,
                                   CefPdfValueCallback,
                                   cef_pdf_value_callback_t>::kWrapperType =
    WT_PDF_VALUE_CALLBACK;