// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=115110934d5c4e5ab927062faabd0617c6208c46$
//

#include "libcef_dll/ctocpp/permission_request_ctocpp.h"
#include "libcef_dll/cpptoc/access_request_cpptoc.h"
#include "libcef_dll/cpptoc/screen_capture_access_request_cpptoc.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefPermissionRequestCToCpp::OnGeolocationShow(const CefString& origin) {
  cef_permission_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_geolocation_show))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: origin; type: string_byref_const
  DCHECK(!origin.empty());
  if (origin.empty())
    return;

  // Execute
  _struct->on_geolocation_show(_struct, origin.GetStruct());
}

NO_SANITIZE("cfi-icall") void CefPermissionRequestCToCpp::OnGeolocationHide() {
  cef_permission_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_geolocation_hide))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->on_geolocation_hide(_struct);
}

NO_SANITIZE("cfi-icall")
void CefPermissionRequestCToCpp::OnPermissionRequest(
    CefRefPtr<CefAccessRequest> request) {
  cef_permission_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_permission_request))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: request; type: refptr_diff
  DCHECK(request.get());
  if (!request.get())
    return;

  // Execute
  _struct->on_permission_request(_struct,
                                 CefAccessRequestCppToC::Wrap(request));
}

NO_SANITIZE("cfi-icall")
void CefPermissionRequestCToCpp::OnPermissionRequestCanceled(
    CefRefPtr<CefAccessRequest> request) {
  cef_permission_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_permission_request_canceled))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: request; type: refptr_diff
  DCHECK(request.get());
  if (!request.get())
    return;

  // Execute
  _struct->on_permission_request_canceled(
      _struct, CefAccessRequestCppToC::Wrap(request));
}

NO_SANITIZE("cfi-icall")
void CefPermissionRequestCToCpp::OnScreenCaptureRequest(
    CefRefPtr<CefScreenCaptureAccessRequest> request) {
  cef_permission_request_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_screen_capture_request))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: request; type: refptr_diff
  DCHECK(request.get());
  if (!request.get())
    return;

  // Execute
  _struct->on_screen_capture_request(
      _struct, CefScreenCaptureAccessRequestCppToC::Wrap(request));
}

// CONSTRUCTOR - Do not edit by hand.

CefPermissionRequestCToCpp::CefPermissionRequestCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefPermissionRequestCToCpp::~CefPermissionRequestCToCpp() {}

template <>
cef_permission_request_t* CefCToCppRefCounted<
    CefPermissionRequestCToCpp,
    CefPermissionRequest,
    cef_permission_request_t>::UnwrapDerived(CefWrapperType type,
                                             CefPermissionRequest* c) {
  NOTREACHED() << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefPermissionRequestCToCpp,
                                   CefPermissionRequest,
                                   cef_permission_request_t>::kWrapperType =
    WT_PERMISSION_REQUEST;
