// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=6660d557213d744f9adbc9f78e59780ede608dd5$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_PERMISSION_REQUEST_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_PERMISSION_REQUEST_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_permission_request_capi.h"
#include "include/cef_permission_request.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class CefPermissionRequestCToCpp
    : public CefCToCppRefCounted<CefPermissionRequestCToCpp,
                                 CefPermissionRequest,
                                 cef_permission_request_t> {
 public:
  CefPermissionRequestCToCpp();
  virtual ~CefPermissionRequestCToCpp();

  // CefPermissionRequest methods.
  void OnGeolocationShow(const CefString& origin) override;
  void OnGeolocationHide() override;
  void OnPermissionRequest(CefRefPtr<CefAccessRequest> request) override;
  void OnPermissionRequestCanceled(
      CefRefPtr<CefAccessRequest> request) override;
  void OnScreenCaptureRequest(
      CefRefPtr<CefScreenCaptureAccessRequest> request) override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_PERMISSION_REQUEST_CTOCPP_H_
