// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=930690bd2985275d115477d6bf61ea93e61cd99d$
//

#include "libcef_dll/ctocpp/post_data_stream_read_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefPostDataStreamReadCallbackCToCpp::OnReadComplete(char* buffer,
                                                         int bytes_read) {
  shutdown_checker::AssertNotShutdown();

  cef_post_data_stream_read_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cont)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: buffer; type: simple_byaddr
  DCHECK(buffer);
  if (!buffer) {
    return;
  }

  // Execute
  _struct->cont(_struct, buffer, bytes_read);
}

// CONSTRUCTOR - Do not edit by hand.

CefPostDataStreamReadCallbackCToCpp::CefPostDataStreamReadCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefPostDataStreamReadCallbackCToCpp::~CefPostDataStreamReadCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_post_data_stream_read_callback_t*
CefCToCppRefCounted<CefPostDataStreamReadCallbackCToCpp,
                    CefPostDataStreamReadCallback,
                    cef_post_data_stream_read_callback_t>::
    UnwrapDerived(CefWrapperType type, CefPostDataStreamReadCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCToCppRefCounted<CefPostDataStreamReadCallbackCToCpp,
                        CefPostDataStreamReadCallback,
                        cef_post_data_stream_read_callback_t>::kWrapperType =
        WT_POST_DATA_STREAM_READ_CALLBACK;
