// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=64b06c55271b7adfa75f2511daa6ab4874ce6400$
//

#include "libcef_dll/ctocpp/post_data_stream_ctocpp.h"
#include "libcef_dll/ctocpp/post_data_stream_init_callback_ctocpp.h"
#include "libcef_dll/ctocpp/post_data_stream_read_callback_ctocpp.h"

// STATIC METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
CefRefPtr<CefPostDataStream> CefPostDataStream::Create() {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  cef_post_data_stream_t *_retval = cef_post_data_stream_create();

  // Return type: refptr_same
  return CefPostDataStreamCToCpp::Wrap(_retval);
}

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefPostDataStreamCToCpp::SetReadCallback(
    CefRefPtr<CefPostDataStreamReadCallback> read_callback) {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, set_read_callback)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: read_callback; type: refptr_same
  DCHECK(read_callback.get());
  if (!read_callback.get()) {
    return;
  }

  // Execute
  _struct->set_read_callback(
      _struct, CefPostDataStreamReadCallbackCToCpp::Unwrap(read_callback));
}

NO_SANITIZE("cfi-icall")
void CefPostDataStreamCToCpp::Init(
    CefRefPtr<CefPostDataStreamInitCallback> init_callback) {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, init)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: init_callback; type: refptr_same
  DCHECK(init_callback.get());
  if (!init_callback.get()) {
    return;
  }

  // Execute
  _struct->init(_struct,
                CefPostDataStreamInitCallbackCToCpp::Unwrap(init_callback));
}

NO_SANITIZE("cfi-icall")
void CefPostDataStreamCToCpp::Read(
    void *buffer, int buf_len,
    CefRefPtr<CefPostDataStreamReadCallback> read_callback) {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, read)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: buffer; type: simple_byaddr
  DCHECK(buffer);
  if (!buffer) {
    return;
  }
  // Verify param: read_callback; type: refptr_same
  DCHECK(read_callback.get());
  if (!read_callback.get()) {
    return;
  }

  // Execute
  _struct->read(_struct, buffer, buf_len,
                CefPostDataStreamReadCallbackCToCpp::Unwrap(read_callback));
}

NO_SANITIZE("cfi-icall") uint64 CefPostDataStreamCToCpp::GetSize() {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_size)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  uint64 _retval = _struct->get_size(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") uint64 CefPostDataStreamCToCpp::GetPosition() {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_position)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  uint64 _retval = _struct->get_position(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") bool CefPostDataStreamCToCpp::IsChunked() {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_chunked)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_chunked(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool CefPostDataStreamCToCpp::HasNullSource() {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, has_null_source)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->has_null_source(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool CefPostDataStreamCToCpp::IsEOF() {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_eof)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_eof(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool CefPostDataStreamCToCpp::IsInMemory() {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_in_memory)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_in_memory(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void CefPostDataStreamCToCpp::Reset() {
  cef_post_data_stream_t *_struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, reset)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->reset(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

CefPostDataStreamCToCpp::CefPostDataStreamCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefPostDataStreamCToCpp::~CefPostDataStreamCToCpp() {}

template <>
cef_post_data_stream_t *
CefCToCppRefCounted<CefPostDataStreamCToCpp, CefPostDataStream,
                    cef_post_data_stream_t>::UnwrapDerived(CefWrapperType type,
                                                           CefPostDataStream
                                                               *c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefPostDataStreamCToCpp, CefPostDataStream,
                                   cef_post_data_stream_t>::kWrapperType =
    WT_POST_DATA_STREAM;
