// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a033180bdefa68c332d3c1748ad683fa6ee29ef8$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_POST_DATA_STREAM_READ_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_POST_DATA_STREAM_READ_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_request_capi.h"
#include "include/cef_request.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefPostDataStreamReadCallbackCToCpp
    : public CefCToCppRefCounted<CefPostDataStreamReadCallbackCToCpp,
                                 CefPostDataStreamReadCallback,
                                 cef_post_data_stream_read_callback_t> {
 public:
  CefPostDataStreamReadCallbackCToCpp();
  virtual ~CefPostDataStreamReadCallbackCToCpp();

  // CefPostDataStreamReadCallback methods.
  void OnReadComplete(char* buffer, int bytes_read) override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_POST_DATA_STREAM_READ_CALLBACK_CTOCPP_H_
