// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f56fbff9a852f4a83251803f4719d5f57d042978$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_POST_DATA_STREAM_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_POST_DATA_STREAM_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_request_capi.h"
#include "include/cef_request.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefPostDataStreamCToCpp
    : public CefCToCppRefCounted<CefPostDataStreamCToCpp,
                                 CefPostDataStream,
                                 cef_post_data_stream_t> {
 public:
  CefPostDataStreamCToCpp();
  virtual ~CefPostDataStreamCToCpp();

  // CefPostDataStream methods.
  void SetReadCallback(
      CefRefPtr<CefPostDataStreamReadCallback> read_callback) override;
  void Init(CefRefPtr<CefPostDataStreamInitCallback> init_callback) override;
  void Read(void* buffer,
            int buf_len,
            CefRefPtr<CefPostDataStreamReadCallback> read_callback) override;
  uint64 GetSize() override;
  uint64 GetPosition() override;
  bool IsChunked() override;
  bool HasNullSource() override;
  bool IsEOF() override;
  bool IsInMemory() override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_POST_DATA_STREAM_CTOCPP_H_
