// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b3cfa171e32c20f5843787c6e5376308e407b406$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_READ_HANDLER_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_READ_HANDLER_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_stream.h"
#include "include/capi/cef_stream_capi_versions.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefReadHandler_0_CToCpp
    : public CefCToCppRefCounted<CefReadHandler_0_CToCpp, CefReadHandler, cef_read_handler_0_t> {
 public:
  CefReadHandler_0_CToCpp();
  virtual ~CefReadHandler_0_CToCpp();

  // CefReadHandler methods.
  size_t Read(void* ptr, size_t size, size_t n) override;
  int Seek(int64_t offset, int whence) override;
  int64_t Tell() override;
  int Eof() override;
  bool MayBlock() override;
};

constexpr auto CefReadHandlerCToCpp_Wrap = CefReadHandler_0_CToCpp::Wrap;
constexpr auto CefReadHandlerCToCpp_Unwrap = CefReadHandler_0_CToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_READ_HANDLER_CTOCPP_H_
