// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=16c0e0036165d9cf13c9284b348ec075d852b843$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_RUN_FILE_DIALOG_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_RUN_FILE_DIALOG_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include <vector>
#include "include/cef_browser.h"
#include "include/capi/cef_browser_capi_versions.h"
#include "include/cef_client.h"
#include "include/capi/cef_client_capi_versions.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefRunFileDialogCallback_0_CToCpp
    : public CefCToCppRefCounted<CefRunFileDialogCallback_0_CToCpp, CefRunFileDialogCallback, cef_run_file_dialog_callback_0_t> {
 public:
  CefRunFileDialogCallback_0_CToCpp();
  virtual ~CefRunFileDialogCallback_0_CToCpp();

  // CefRunFileDialogCallback methods.
  void OnFileDialogDismissed(const std::vector<CefString>& file_paths) override;
};

constexpr auto CefRunFileDialogCallbackCToCpp_Wrap = CefRunFileDialogCallback_0_CToCpp::Wrap;
constexpr auto CefRunFileDialogCallbackCToCpp_Unwrap = CefRunFileDialogCallback_0_CToCpp::Unwrap;

#endif  // CEF_LIBCEF_DLL_CTOCPP_RUN_FILE_DIALOG_CALLBACK_CTOCPP_H_
