// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b516314ad82c4737d78dc8aaf6cf687881b4be35$
//

#include "libcef_dll/ctocpp/screen_capture_callback_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefScreenCaptureCallbackCToCpp::OnStateChange(int32_t nweb_id,
                                                   const CefString& sessionid,
                                                   int32_t code) {
  shutdown_checker::AssertNotShutdown();

  cef_screen_capture_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_state_change)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: sessionid; type: string_byref_const
  DCHECK(!sessionid.empty());
  if (sessionid.empty()) {
    return;
  }

  // Execute
  _struct->on_state_change(_struct, nweb_id, sessionid.GetStruct(), code);
}

// CONSTRUCTOR - Do not edit by hand.

CefScreenCaptureCallbackCToCpp::CefScreenCaptureCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefScreenCaptureCallbackCToCpp::~CefScreenCaptureCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_screen_capture_callback_t* CefCToCppRefCounted<
    CefScreenCaptureCallbackCToCpp,
    CefScreenCaptureCallback,
    cef_screen_capture_callback_t>::UnwrapDerived(CefWrapperType type,
                                                  CefScreenCaptureCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCToCppRefCounted<CefScreenCaptureCallbackCToCpp,
                        CefScreenCaptureCallback,
                        cef_screen_capture_callback_t>::kWrapperType =
        WT_SCREEN_CAPTURE_CALLBACK;
