// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=37746c77aa2fdaefef4d1fa3a8dcde7b7a6b8cba$
//

#include "libcef_dll/ctocpp/select_popup_callback_ctocpp.h"

#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefSelectPopupCallbackCToCpp::Continue(const std::vector<int>& indices) {
  shutdown_checker::AssertNotShutdown();

  cef_select_popup_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cont)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: indices; type: simple_vec_byref_const
  const size_t indicesCount = indices.size();
  int* indicesList = NULL;
  if (indicesCount > 0) {
    indicesList = new int[indicesCount];
    DCHECK(indicesList);
    if (indicesList) {
      for (size_t i = 0; i < indicesCount; ++i) {
        indicesList[i] = indices[i];
      }
    }
  }

  // Execute
  _struct->cont(_struct, indicesCount, indicesList);

  // Restore param:indices; type: simple_vec_byref_const
  if (indicesList) {
    delete[] indicesList;
  }
}

NO_SANITIZE("cfi-icall") void CefSelectPopupCallbackCToCpp::Cancel() {
  shutdown_checker::AssertNotShutdown();

  cef_select_popup_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cancel)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cancel(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

CefSelectPopupCallbackCToCpp::CefSelectPopupCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefSelectPopupCallbackCToCpp::~CefSelectPopupCallbackCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_select_popup_callback_t* CefCToCppRefCounted<
    CefSelectPopupCallbackCToCpp,
    CefSelectPopupCallback,
    cef_select_popup_callback_t>::UnwrapDerived(CefWrapperType type,
                                                CefSelectPopupCallback* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefSelectPopupCallbackCToCpp,
                                   CefSelectPopupCallback,
                                   cef_select_popup_callback_t>::kWrapperType =
    WT_SELECT_POPUP_CALLBACK;
