// Copyright (c) 2022 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=0de5941ff724adcd6ca8fcb5e1a5266143afa820$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_SELECT_CLIENT_CERTIFICATE_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_SELECT_CLIENT_CERTIFICATE_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_callback_capi.h"
#include "include/cef_callback.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefSelectClientCertificateCallbackCToCpp
    : public CefCToCppRefCounted<CefSelectClientCertificateCallbackCToCpp,
                                 CefSelectClientCertificateCallback,
                                 cef_select_client_certificate_callback_t> {
 public:
  CefSelectClientCertificateCallbackCToCpp();
  virtual ~CefSelectClientCertificateCallbackCToCpp();

  // CefSelectClientCertificateCallback methods.
  void Select(const CefString& private_key_file,
              const CefString& cert_chain_file) override;
  void Cancel() override;
  void Ignore() override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_SELECT_CLIENT_CERTIFICATE_CALLBACK_CTOCPP_H_
