// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=d9376a2376082b68ec98decd89eb8100fdf7093c$
//

#include "libcef_dll/ctocpp/web_message_receiver_ctocpp.h"
#include "libcef_dll/cpptoc/value_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefWebMessageReceiverCToCpp::OnMessage(CefRefPtr<CefValue> message) {
  shutdown_checker::AssertNotShutdown();

  cef_web_message_receiver_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_message))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: message; type: refptr_diff
  DCHECK(message.get());
  if (!message.get())
    return;

  // Execute
  _struct->on_message(_struct, CefValueCppToC::Wrap(message));
}

// CONSTRUCTOR - Do not edit by hand.

CefWebMessageReceiverCToCpp::CefWebMessageReceiverCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefWebMessageReceiverCToCpp::~CefWebMessageReceiverCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_web_message_receiver_t* CefCToCppRefCounted<
    CefWebMessageReceiverCToCpp,
    CefWebMessageReceiver,
    cef_web_message_receiver_t>::UnwrapDerived(CefWrapperType type,
                                               CefWebMessageReceiver* c) {
  NOTREACHED() << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefWebMessageReceiverCToCpp,
                                   CefWebMessageReceiver,
                                   cef_web_message_receiver_t>::kWrapperType =
    WT_WEB_MESSAGE_RECEIVER;
