// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e9db4d4b0737f171f5d1bb0bddcce68e992fffe3$
//

#include "libcef_dll/ctocpp/web_extension_api_handler_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefWebExtensionApiHandlerCToCpp::OnUpdateTabUrl(int tab_id,
                                                     const CefString& url) {
  shutdown_checker::AssertNotShutdown();

  cef_web_extension_api_handler_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, on_update_tab_url)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: url; type: string_byref_const
  DCHECK(!url.empty());
  if (url.empty()) {
    return;
  }

  // Execute
  _struct->on_update_tab_url(_struct, tab_id, url.GetStruct());
}

// CONSTRUCTOR - Do not edit by hand.

CefWebExtensionApiHandlerCToCpp::CefWebExtensionApiHandlerCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefWebExtensionApiHandlerCToCpp::~CefWebExtensionApiHandlerCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_web_extension_api_handler_t* CefCToCppRefCounted<
    CefWebExtensionApiHandlerCToCpp,
    CefWebExtensionApiHandler,
    cef_web_extension_api_handler_t>::UnwrapDerived(CefWrapperType type,
                                                    CefWebExtensionApiHandler*
                                                        c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCToCppRefCounted<CefWebExtensionApiHandlerCToCpp,
                        CefWebExtensionApiHandler,
                        cef_web_extension_api_handler_t>::kWrapperType =
        WT_WEB_EXTENSION_API_HANDLER;
