// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f01cdd91598d151bee833a80f50f550adda82d37$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_WEB_STORAGE_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_WEB_STORAGE_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_web_storage_capi.h"
#include "include/cef_web_storage.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefWebStorageCToCpp : public CefCToCppRefCounted<CefWebStorageCToCpp,
                                                       CefWebStorage,
                                                       cef_web_storage_t> {
 public:
  CefWebStorageCToCpp();
  virtual ~CefWebStorageCToCpp();

  // CefWebStorage methods.
  void DeleteAllData() override;
  void DeleteOrigin(const CefString& origin) override;
  void GetOrigins(CefRefPtr<CefGetOriginsCallback> callback) override;
  void GetOriginQuota(
      const CefString& origin,
      CefRefPtr<CefGetOriginUsageOrQuotaCallback> callback) override;
  void GetOriginUsage(
      const CefString& origin,
      CefRefPtr<CefGetOriginUsageOrQuotaCallback> callback) override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_WEB_STORAGE_CTOCPP_H_
