// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=4fee9cda8c46061cdba99dd8f66380547eead6e3$
//

#include "libcef_dll/ctocpp/web_storage_ctocpp.h"
#include "libcef_dll/cpptoc/completion_callback_cpptoc.h"
#include "libcef_dll/cpptoc/get_origin_usage_or_quota_callback_cpptoc.h"
#include "libcef_dll/cpptoc/get_origins_callback_cpptoc.h"
#include "libcef_dll/cpptoc/get_password_callback_cpptoc.h"
#include "libcef_dll/cpptoc/get_saved_passwords_callback_cpptoc.h"

// STATIC METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
CefRefPtr<CefWebStorage> CefWebStorage::GetGlobalManager(
    CefRefPtr<CefCompletionCallback> callback) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: callback

  // Execute
  cef_web_storage_t* _retval = cef_web_storage_get_global_manager(
      CefCompletionCallbackCppToC::Wrap(callback));

  // Return type: refptr_same
  return CefWebStorageCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
CefRefPtr<CefWebStorage> CefWebStorage::GetGlobalIncognitoManager(
    CefRefPtr<CefCompletionCallback> callback) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: callback

  // Execute
  cef_web_storage_t* _retval = cef_web_storage_get_global_incognito_manager(
      CefCompletionCallbackCppToC::Wrap(callback));

  // Return type: refptr_same
  return CefWebStorageCToCpp::Wrap(_retval);
}

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void CefWebStorageCToCpp::DeleteAllData() {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, delete_all_data)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->delete_all_data(_struct);
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::DeleteOrigin(const CefString& origin) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, delete_origin)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: origin; type: string_byref_const
  DCHECK(!origin.empty());
  if (origin.empty()) {
    return;
  }

  // Execute
  _struct->delete_origin(_struct, origin.GetStruct());
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::GetOrigins(
    CefRefPtr<CefGetOriginsCallback> callback) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_origins)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: callback

  // Execute
  _struct->get_origins(_struct, CefGetOriginsCallbackCppToC::Wrap(callback));
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::GetOriginQuota(
    const CefString& origin,
    CefRefPtr<CefGetOriginUsageOrQuotaCallback> callback) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_origin_quota)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: origin, callback

  // Execute
  _struct->get_origin_quota(
      _struct, origin.GetStruct(),
      CefGetOriginUsageOrQuotaCallbackCppToC::Wrap(callback));
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::GetOriginUsage(
    const CefString& origin,
    CefRefPtr<CefGetOriginUsageOrQuotaCallback> callback) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_origin_usage)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: origin, callback

  // Execute
  _struct->get_origin_usage(
      _struct, origin.GetStruct(),
      CefGetOriginUsageOrQuotaCallbackCppToC::Wrap(callback));
}

NO_SANITIZE("cfi-icall") void CefWebStorageCToCpp::ClearPassword() {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, clear_password)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->clear_password(_struct);
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::RemovePassword(const CefString& url,
                                         const CefString& username) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, remove_password)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: url; type: string_byref_const
  DCHECK(!url.empty());
  if (url.empty()) {
    return;
  }
  // Verify param: username; type: string_byref_const
  DCHECK(!username.empty());
  if (username.empty()) {
    return;
  }

  // Execute
  _struct->remove_password(_struct, url.GetStruct(), username.GetStruct());
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::ModifyPassword(const CefString& url,
                                         const CefString& old_username,
                                         const CefString& new_username,
                                         const CefString& new_password) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, modify_password)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: url; type: string_byref_const
  DCHECK(!url.empty());
  if (url.empty()) {
    return;
  }
  // Verify param: old_username; type: string_byref_const
  DCHECK(!old_username.empty());
  if (old_username.empty()) {
    return;
  }
  // Verify param: new_username; type: string_byref_const
  DCHECK(!new_username.empty());
  if (new_username.empty()) {
    return;
  }
  // Verify param: new_password; type: string_byref_const
  DCHECK(!new_password.empty());
  if (new_password.empty()) {
    return;
  }

  // Execute
  _struct->modify_password(_struct, url.GetStruct(), old_username.GetStruct(),
                           new_username.GetStruct(), new_password.GetStruct());
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::RemovePasswordByUrl(const CefString& url) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, remove_password_by_url)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: url; type: string_byref_const
  DCHECK(!url.empty());
  if (url.empty()) {
    return;
  }

  // Execute
  _struct->remove_password_by_url(_struct, url.GetStruct());
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::GetPassword(
    const CefString& url,
    const CefString& username,
    CefRefPtr<CefGetPasswordCallback> callback) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_password)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: url, username, callback

  // Execute
  _struct->get_password(_struct, url.GetStruct(), username.GetStruct(),
                        CefGetPasswordCallbackCppToC::Wrap(callback));
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::GetSavedPasswordsInfo(
    CefRefPtr<CefGetSavedPasswordsCallback> callback) {
  cef_web_storage_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_saved_passwords_info)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: callback

  // Execute
  _struct->get_saved_passwords_info(
      _struct, CefGetSavedPasswordsCallbackCppToC::Wrap(callback));
}

NO_SANITIZE("cfi-icall")
void CefWebStorageCToCpp::MigratePasswordsInfo() {
  return;
}

// CONSTRUCTOR - Do not edit by hand.

CefWebStorageCToCpp::CefWebStorageCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefWebStorageCToCpp::~CefWebStorageCToCpp() {}

template <>
cef_web_storage_t*
CefCToCppRefCounted<CefWebStorageCToCpp, CefWebStorage, cef_web_storage_t>::
    UnwrapDerived(CefWrapperType type, CefWebStorage* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCToCppRefCounted<CefWebStorageCToCpp,
                                   CefWebStorage,
                                   cef_web_storage_t>::kWrapperType =
    WT_WEB_STORAGE;
