// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=2c7237d07b2630c06a78b23916330289d3b9cf9c$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_TEST_TRANSLATOR_TEST_REF_PTR_LIBRARY_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_TEST_TRANSLATOR_TEST_REF_PTR_LIBRARY_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/test/cef_translator_test.h"
#include "include/capi/test/cef_translator_test_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefTranslatorTestRefPtrLibrary_0_CppToC
    : public CefCppToCRefCounted<CefTranslatorTestRefPtrLibrary_0_CppToC, CefTranslatorTestRefPtrLibrary, cef_translator_test_ref_ptr_library_0_t> {
 public:
  CefTranslatorTestRefPtrLibrary_0_CppToC();
  virtual ~CefTranslatorTestRefPtrLibrary_0_CppToC();
};

constexpr auto CefTranslatorTestRefPtrLibraryCppToC_Wrap = CefTranslatorTestRefPtrLibrary_0_CppToC::Wrap;
constexpr auto CefTranslatorTestRefPtrLibraryCppToC_Unwrap = CefTranslatorTestRefPtrLibrary_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_TEST_TRANSLATOR_TEST_REF_PTR_LIBRARY_CPPTOC_H_
