// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=41d5919c2dd767426711253b5a7fd741b283682d$
//

#include "libcef_dll/cpptoc/access_request_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

cef_string_userfree_t CEF_CALLBACK
access_request_origin(struct _cef_access_request_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return NULL;
  }

  // Execute
  CefString _retval = CefAccessRequestCppToC::Get(self)->Origin();

  // Return type: string
  return _retval.DetachToUserFree();
}

int CEF_CALLBACK
access_request_resource_acess_id(struct _cef_access_request_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int _retval = CefAccessRequestCppToC::Get(self)->ResourceAcessId();

  // Return type: simple
  return _retval;
}

void CEF_CALLBACK
access_request_report_request_result(struct _cef_access_request_t* self,
                                     int allowed) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefAccessRequestCppToC::Get(self)->ReportRequestResult(allowed ? true
                                                                 : false);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefAccessRequestCppToC::CefAccessRequestCppToC() {
  GetStruct()->origin = access_request_origin;
  GetStruct()->resource_acess_id = access_request_resource_acess_id;
  GetStruct()->report_request_result = access_request_report_request_result;
}

// DESTRUCTOR - Do not edit by hand.

CefAccessRequestCppToC::~CefAccessRequestCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefAccessRequest> CefCppToCRefCounted<
    CefAccessRequestCppToC,
    CefAccessRequest,
    cef_access_request_t>::UnwrapDerived(CefWrapperType type,
                                         cef_access_request_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefAccessRequestCppToC,
                                   CefAccessRequest,
                                   cef_access_request_t>::kWrapperType =
    WT_ACCESS_REQUEST;
