// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=44c32953a5dc70e64d35222732817d6b065f0e33$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_ACCESS_REQUEST_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_ACCESS_REQUEST_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_permission_request_capi.h"
#include "include/cef_permission_request.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class CefAccessRequestCppToC
    : public CefCppToCRefCounted<CefAccessRequestCppToC,
                                 CefAccessRequest,
                                 cef_access_request_t> {
 public:
  CefAccessRequestCppToC();
  virtual ~CefAccessRequestCppToC();
};

#endif  // CEF_LIBCEF_DLL_CPPTOC_ACCESS_REQUEST_CPPTOC_H_
