// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=ebe934a0127d55ef4837fc5a93230a236217627a$
//

#include "libcef_dll/cpptoc/ads_block_manager_cpptoc.h"

#include "libcef_dll/ctocpp/completion_callback_ctocpp.h"
#include "libcef_dll/transfer_util.h"

// GLOBAL FUNCTIONS - Body may be edited by hand.

CEF_EXPORT cef_ads_block_manager_t* cef_ads_block_manager_get_global(
    struct _cef_completion_callback_t* callback) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: callback

  // Execute
  CefRefPtr<CefAdsBlockManager> _retval =
      CefAdsBlockManager::GetGlobalAdsBlockManager(
          CefCompletionCallbackCToCpp::Wrap(callback));

  // Return type: refptr_same
  return CefAdsBlockManagerCppToC::Wrap(_retval);
}

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
ads_block_manager_set_ads_block_rules(struct _cef_ads_block_manager_t* self,
                                      const cef_string_t* rulesFile,
                                      int replace) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: rulesFile; type: string_byref_const
  DCHECK(rulesFile);
  if (!rulesFile) {
    return;
  }

  // Execute
  CefAdsBlockManagerCppToC::Get(self)->SetAdsBlockRules(CefString(rulesFile),
                                                        replace ? true : false);
}

void CEF_CALLBACK ads_block_manager_add_ads_block_disallowed_list(
    struct _cef_ads_block_manager_t* self,
    cef_string_list_t domainSuffixes) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: domainSuffixes; type: string_vec_byref_const
  DCHECK(domainSuffixes);
  if (!domainSuffixes) {
    return;
  }

  // Translate param: domainSuffixes; type: string_vec_byref_const
  std::vector<CefString> domainSuffixesList;
  transfer_string_list_contents(domainSuffixes, domainSuffixesList);

  // Execute
  CefAdsBlockManagerCppToC::Get(self)->AddAdsBlockDisallowedList(
      domainSuffixesList);
}

void CEF_CALLBACK ads_block_manager_remove_ads_block_disallowed_list(
    struct _cef_ads_block_manager_t* self,
    cef_string_list_t domainSuffixes) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: domainSuffixes; type: string_vec_byref_const
  DCHECK(domainSuffixes);
  if (!domainSuffixes) {
    return;
  }

  // Translate param: domainSuffixes; type: string_vec_byref_const
  std::vector<CefString> domainSuffixesList;
  transfer_string_list_contents(domainSuffixes, domainSuffixesList);

  // Execute
  CefAdsBlockManagerCppToC::Get(self)->RemoveAdsBlockDisallowedList(
      domainSuffixesList);
}

void CEF_CALLBACK ads_block_manager_clear_ads_block_disallowed_list(
    struct _cef_ads_block_manager_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefAdsBlockManagerCppToC::Get(self)->ClearAdsBlockDisallowedList();
}

void CEF_CALLBACK ads_block_manager_add_ads_block_allowed_list(
    struct _cef_ads_block_manager_t* self,
    cef_string_list_t domainSuffixes) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: domainSuffixes; type: string_vec_byref_const
  DCHECK(domainSuffixes);
  if (!domainSuffixes) {
    return;
  }

  // Translate param: domainSuffixes; type: string_vec_byref_const
  std::vector<CefString> domainSuffixesList;
  transfer_string_list_contents(domainSuffixes, domainSuffixesList);

  // Execute
  CefAdsBlockManagerCppToC::Get(self)->AddAdsBlockAllowedList(
      domainSuffixesList);
}

void CEF_CALLBACK ads_block_manager_remove_ads_block_allowed_list(
    struct _cef_ads_block_manager_t* self,
    cef_string_list_t domainSuffixes) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: domainSuffixes; type: string_vec_byref_const
  DCHECK(domainSuffixes);
  if (!domainSuffixes) {
    return;
  }

  // Translate param: domainSuffixes; type: string_vec_byref_const
  std::vector<CefString> domainSuffixesList;
  transfer_string_list_contents(domainSuffixes, domainSuffixesList);

  // Execute
  CefAdsBlockManagerCppToC::Get(self)->RemoveAdsBlockAllowedList(
      domainSuffixesList);
}

void CEF_CALLBACK ads_block_manager_clear_ads_block_allowed_list(
    struct _cef_ads_block_manager_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefAdsBlockManagerCppToC::Get(self)->ClearAdsBlockAllowedList();
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefAdsBlockManagerCppToC::CefAdsBlockManagerCppToC() {
  GetStruct()->set_ads_block_rules = ads_block_manager_set_ads_block_rules;
  GetStruct()->add_ads_block_disallowed_list =
      ads_block_manager_add_ads_block_disallowed_list;
  GetStruct()->remove_ads_block_disallowed_list =
      ads_block_manager_remove_ads_block_disallowed_list;
  GetStruct()->clear_ads_block_disallowed_list =
      ads_block_manager_clear_ads_block_disallowed_list;
  GetStruct()->add_ads_block_allowed_list =
      ads_block_manager_add_ads_block_allowed_list;
  GetStruct()->remove_ads_block_allowed_list =
      ads_block_manager_remove_ads_block_allowed_list;
  GetStruct()->clear_ads_block_allowed_list =
      ads_block_manager_clear_ads_block_allowed_list;
}

// DESTRUCTOR - Do not edit by hand.

CefAdsBlockManagerCppToC::~CefAdsBlockManagerCppToC() {}

template <>
CefRefPtr<CefAdsBlockManager> CefCppToCRefCounted<
    CefAdsBlockManagerCppToC,
    CefAdsBlockManager,
    cef_ads_block_manager_t>::UnwrapDerived(CefWrapperType type,
                                            cef_ads_block_manager_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefAdsBlockManagerCppToC,
                                   CefAdsBlockManager,
                                   cef_ads_block_manager_t>::kWrapperType =
    WT_ADS_BLOCK_MANAGER;
