// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=5ea64009b5943c027b2bd361c0291e6a3ab37816$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_AUTH_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_AUTH_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_auth_callback.h"
#include "include/capi/cef_auth_callback_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefAuthCallback_0_CppToC
    : public CefCppToCRefCounted<CefAuthCallback_0_CppToC, CefAuthCallback, cef_auth_callback_0_t> {
 public:
  CefAuthCallback_0_CppToC();
  virtual ~CefAuthCallback_0_CppToC();
};

constexpr auto CefAuthCallbackCppToC_Wrap = CefAuthCallback_0_CppToC::Wrap;
constexpr auto CefAuthCallbackCppToC_Unwrap = CefAuthCallback_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_AUTH_CALLBACK_CPPTOC_H_
