// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c59d2547510f8c98966e003c7825b48f02f561f7$
//

#include "libcef_dll/cpptoc/cache_options_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

cef_string_map_t CEF_CALLBACK
cache_options_get_response_headers(struct _cef_cache_options_t *self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return nullptr;
  }

  // Execute
  cef_string_map_t _retval =
      CefCacheOptionsCppToC::Get(self)->GetResponseHeaders();

  // Return type: simple
  return _retval;
}

} // namespace

// CONSTRUCTOR - Do not edit by hand.

CefCacheOptionsCppToC::CefCacheOptionsCppToC() {
  GetStruct()->get_response_headers = cache_options_get_response_headers;
}

// DESTRUCTOR - Do not edit by hand.

CefCacheOptionsCppToC::~CefCacheOptionsCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefCacheOptions>
CefCppToCRefCounted<CefCacheOptionsCppToC, CefCacheOptions,
                    cef_cache_options_t>::UnwrapDerived(CefWrapperType type,
                                                        cef_cache_options_t
                                                            *s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefCacheOptionsCppToC, CefCacheOptions,
                                   cef_cache_options_t>::kWrapperType =
    WT_CACHE_OPTIONS;
