// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b1b5b07c75ae0bdb48510c5a7bcc5aa0e31e7991$
//

#include "libcef_dll/cpptoc/data_base_cpptoc.h"
#include "libcef_dll/transfer_util.h"

// GLOBAL FUNCTIONS - Body may be edited by hand.

CEF_EXPORT cef_data_base_t* cef_data_base_get_global() {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  CefRefPtr<CefDataBase> _retval = CefDataBase::GetGlobalDataBase();

  // Return type: refptr_same
  return CefDataBaseCppToC::Wrap(_retval);
}

CEF_EXPORT cef_data_base_t* cef_data_base_get_global_incognito() {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  CefRefPtr<CefDataBase> _retval = CefDataBase::GetGlobalIncognitoDataBase();

  // Return type: refptr_same
  return CefDataBaseCppToC::Wrap(_retval);
}

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
data_base_delete_http_auth_credentials(struct _cef_data_base_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefDataBaseCppToC::Get(self)->DeleteHttpAuthCredentials();
}

int CEF_CALLBACK
data_base_exist_http_auth_credentials(struct _cef_data_base_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  bool _retval = CefDataBaseCppToC::Get(self)->ExistHttpAuthCredentials();

  // Return type: bool
  return _retval;
}

void CEF_CALLBACK
data_base_save_http_auth_credentials(struct _cef_data_base_t* self,
                                     const cef_string_t* host,
                                     const cef_string_t* realm,
                                     const cef_string_t* username,
                                     const char* password) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: host; type: string_byref_const
  DCHECK(host);
  if (!host) {
    return;
  }
  // Verify param: realm; type: string_byref_const
  DCHECK(realm);
  if (!realm) {
    return;
  }
  // Verify param: username; type: string_byref_const
  DCHECK(username);
  if (!username) {
    return;
  }
  // Verify param: password; type: simple_byaddr
  DCHECK(password);
  if (!password) {
    return;
  }

  // Execute
  CefDataBaseCppToC::Get(self)->SaveHttpAuthCredentials(
      CefString(host), CefString(realm), CefString(username), password);
}

void CEF_CALLBACK
data_base_get_http_auth_credentials(struct _cef_data_base_t* self,
                                    const cef_string_t* host,
                                    const cef_string_t* realm,
                                    cef_string_t* username,
                                    char* password,
                                    uint32_t passwordSize) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: host; type: string_byref_const
  DCHECK(host);
  if (!host) {
    return;
  }
  // Verify param: realm; type: string_byref_const
  DCHECK(realm);
  if (!realm) {
    return;
  }
  // Verify param: username; type: string_byref
  DCHECK(username);
  if (!username) {
    return;
  }
  // Verify param: password; type: simple_byaddr
  DCHECK(password);
  if (!password) {
    return;
  }

  // Translate param: username; type: string_byref
  CefString usernameStr(username);

  // Execute
  CefDataBaseCppToC::Get(self)->GetHttpAuthCredentials(
      CefString(host), CefString(realm), usernameStr, password, passwordSize);
}

int CEF_CALLBACK
data_base_exist_permission_by_origin(struct _cef_data_base_t* self,
                                     const cef_string_t* origin,
                                     int type) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }
  // Verify param: origin; type: string_byref_const
  DCHECK(origin);
  if (!origin) {
    return 0;
  }

  // Execute
  bool _retval = CefDataBaseCppToC::Get(self)->ExistPermissionByOrigin(
      CefString(origin), type);

  // Return type: bool
  return _retval;
}

int CEF_CALLBACK
data_base_get_permission_result_by_origin(struct _cef_data_base_t* self,
                                          const cef_string_t* origin,
                                          int type,
                                          int* result) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }
  // Verify param: origin; type: string_byref_const
  DCHECK(origin);
  if (!origin) {
    return 0;
  }
  // Verify param: result; type: bool_byref
  DCHECK(result);
  if (!result) {
    return 0;
  }

  // Translate param: result; type: bool_byref
  bool resultBool = (result && *result) ? true : false;

  // Execute
  bool _retval = CefDataBaseCppToC::Get(self)->GetPermissionResultByOrigin(
      CefString(origin), type, resultBool);

  // Restore param: result; type: bool_byref
  if (result) {
    *result = resultBool ? true : false;
  }

  // Return type: bool
  return _retval;
}

void CEF_CALLBACK
data_base_set_permission_by_origin(struct _cef_data_base_t* self,
                                   const cef_string_t* origin,
                                   int type,
                                   int result) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: origin; type: string_byref_const
  DCHECK(origin);
  if (!origin) {
    return;
  }

  // Execute
  CefDataBaseCppToC::Get(self)->SetPermissionByOrigin(CefString(origin), type,
                                                      result ? true : false);
}

void CEF_CALLBACK
data_base_clear_permission_by_origin(struct _cef_data_base_t* self,
                                     const cef_string_t* origin,
                                     int type) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: origin; type: string_byref_const
  DCHECK(origin);
  if (!origin) {
    return;
  }

  // Execute
  CefDataBaseCppToC::Get(self)->ClearPermissionByOrigin(CefString(origin),
                                                        type);
}

void CEF_CALLBACK data_base_clear_all_permission(struct _cef_data_base_t* self,
                                                 int type) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefDataBaseCppToC::Get(self)->ClearAllPermission(type);
}

void CEF_CALLBACK
data_base_get_origins_by_permission(struct _cef_data_base_t* self,
                                    int type,
                                    cef_string_list_t origins) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: origins; type: string_vec_byref
  DCHECK(origins);
  if (!origins) {
    return;
  }

  // Translate param: origins; type: string_vec_byref
  std::vector<CefString> originsList;
  transfer_string_list_contents(origins, originsList);

  // Execute
  CefDataBaseCppToC::Get(self)->GetOriginsByPermission(type, originsList);

  // Restore param: origins; type: string_vec_byref
  cef_string_list_clear(origins);
  transfer_string_list_contents(originsList, origins);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefDataBaseCppToC::CefDataBaseCppToC() {
  GetStruct()->delete_http_auth_credentials =
      data_base_delete_http_auth_credentials;
  GetStruct()->exist_http_auth_credentials =
      data_base_exist_http_auth_credentials;
  GetStruct()->save_http_auth_credentials =
      data_base_save_http_auth_credentials;
  GetStruct()->get_http_auth_credentials = data_base_get_http_auth_credentials;
  GetStruct()->exist_permission_by_origin =
      data_base_exist_permission_by_origin;
  GetStruct()->get_permission_result_by_origin =
      data_base_get_permission_result_by_origin;
  GetStruct()->set_permission_by_origin = data_base_set_permission_by_origin;
  GetStruct()->clear_permission_by_origin =
      data_base_clear_permission_by_origin;
  GetStruct()->clear_all_permission = data_base_clear_all_permission;
  GetStruct()->get_origins_by_permission = data_base_get_origins_by_permission;
}

// DESTRUCTOR - Do not edit by hand.

CefDataBaseCppToC::~CefDataBaseCppToC() {}

template <>
CefRefPtr<CefDataBase>
CefCppToCRefCounted<CefDataBaseCppToC, CefDataBase, cef_data_base_t>::
    UnwrapDerived(CefWrapperType type, cef_data_base_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefDataBaseCppToC,
                                   CefDataBase,
                                   cef_data_base_t>::kWrapperType =
    WT_DATA_BASE;
