// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=dedd8595fcd85cd64e35ff00bd028976ca083375$
//

#include "libcef_dll/cpptoc/date_time_chooser_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
date_time_chooser_callback_cont(struct _cef_date_time_chooser_callback_t* self,
                                int success,
                                double dialog_value) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefDateTimeChooserCallbackCppToC::Get(self)->Continue(success ? true : false,
                                                        dialog_value);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefDateTimeChooserCallbackCppToC::CefDateTimeChooserCallbackCppToC() {
  GetStruct()->cont = date_time_chooser_callback_cont;
}

// DESTRUCTOR - Do not edit by hand.

CefDateTimeChooserCallbackCppToC::~CefDateTimeChooserCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefDateTimeChooserCallback>
CefCppToCRefCounted<CefDateTimeChooserCallbackCppToC,
                    CefDateTimeChooserCallback,
                    cef_date_time_chooser_callback_t>::
    UnwrapDerived(CefWrapperType type, cef_date_time_chooser_callback_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCppToCRefCounted<CefDateTimeChooserCallbackCppToC,
                        CefDateTimeChooserCallback,
                        cef_date_time_chooser_callback_t>::kWrapperType =
        WT_DATE_TIME_CHOOSER_CALLBACK;
