// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e9148b51bd8de1851d92974a97765448cd44d09b$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_DOMDOCUMENT_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_DOMDOCUMENT_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_dom.h"
#include "include/capi/cef_dom_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefDOMDocument_0_CppToC
    : public CefCppToCRefCounted<CefDOMDocument_0_CppToC, CefDOMDocument, cef_domdocument_0_t> {
 public:
  CefDOMDocument_0_CppToC();
  virtual ~CefDOMDocument_0_CppToC();
};

constexpr auto CefDOMDocumentCppToC_Wrap = CefDOMDocument_0_CppToC::Wrap;
constexpr auto CefDOMDocumentCppToC_Unwrap = CefDOMDocument_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_DOMDOCUMENT_CPPTOC_H_
