// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f35747d7dbf795d1fcd33f75d75e7df6a022f91e$
//

#include "libcef_dll/cpptoc/first_meaningful_paint_details_cpptoc.h"

#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

int64_t CEF_CALLBACK first_meaningful_paint_details_get_navigation_start_time(
    struct _cef_first_meaningful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int64_t _retval =
      CefFirstMeaningfulPaintDetailsCppToC::Get(self)->GetNavigationStartTime();

  // Return type: simple
  return _retval;
}

int64_t CEF_CALLBACK
first_meaningful_paint_details_get_first_meaningful_paint_time(
    struct _cef_first_meaningful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int64_t _retval = CefFirstMeaningfulPaintDetailsCppToC::Get(self)
                        ->GetFirstMeaningfulPaintTime();

  // Return type: simple
  return _retval;
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefFirstMeaningfulPaintDetailsCppToC::CefFirstMeaningfulPaintDetailsCppToC() {
  GetStruct()->get_navigation_start_time =
      first_meaningful_paint_details_get_navigation_start_time;
  GetStruct()->get_first_meaningful_paint_time =
      first_meaningful_paint_details_get_first_meaningful_paint_time;
}

// DESTRUCTOR - Do not edit by hand.

CefFirstMeaningfulPaintDetailsCppToC::~CefFirstMeaningfulPaintDetailsCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefFirstMeaningfulPaintDetails>
CefCppToCRefCounted<CefFirstMeaningfulPaintDetailsCppToC,
                    CefFirstMeaningfulPaintDetails,
                    cef_first_meaningful_paint_details_t>::
    UnwrapDerived(CefWrapperType type,
                  cef_first_meaningful_paint_details_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCppToCRefCounted<CefFirstMeaningfulPaintDetailsCppToC,
                        CefFirstMeaningfulPaintDetails,
                        cef_first_meaningful_paint_details_t>::kWrapperType =
        WT_FIRST_MEANINGFUL_PAINT_DETAILS;
