// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=cc1557a7c6d8a1272f0931a4679f18103b9a7a89$
//

#include "libcef_dll/cpptoc/form_handler_cpptoc.h"
#include "libcef_dll/ctocpp/browser_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK form_handler_on_form_editing_state_changed(
    struct _cef_form_handler_t *self, cef_browser_t *browser, int is_editing) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return;
  // Verify param: browser; type: refptr_diff
  DCHECK(browser);
  if (!browser)
    return;

  // Execute
  CefFormHandlerCppToC::Get(self)->OnFormEditingStateChanged(
      CefBrowserCToCpp::Wrap(browser), is_editing ? true : false);
}

} // namespace

// CONSTRUCTOR - Do not edit by hand.

CefFormHandlerCppToC::CefFormHandlerCppToC() {
  GetStruct()->on_form_editing_state_changed =
      form_handler_on_form_editing_state_changed;
}

// DESTRUCTOR - Do not edit by hand.

CefFormHandlerCppToC::~CefFormHandlerCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefFormHandler>
CefCppToCRefCounted<CefFormHandlerCppToC, CefFormHandler,
                    cef_form_handler_t>::UnwrapDerived(CefWrapperType type,
                                                       cef_form_handler_t *s) {
  NOTREACHED() << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefFormHandlerCppToC, CefFormHandler,
                                   cef_form_handler_t>::kWrapperType =
    WT_FORM_HANDLER;
