// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=d2ff4942003f24c5f739c063199e1de6256d477d$
//

#include "libcef_dll/cpptoc/gesture_event_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
gesture_event_callback_continue_task(struct _cef_gesture_event_callback_t* self,
                                     int result) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefGestureEventCallbackCppToC::Get(self)->ContinueTask(result ? true : false);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefGestureEventCallbackCppToC::CefGestureEventCallbackCppToC() {
  GetStruct()->continue_task = gesture_event_callback_continue_task;
}

// DESTRUCTOR - Do not edit by hand.

CefGestureEventCallbackCppToC::~CefGestureEventCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefGestureEventCallback> CefCppToCRefCounted<
    CefGestureEventCallbackCppToC,
    CefGestureEventCallback,
    cef_gesture_event_callback_t>::UnwrapDerived(CefWrapperType type,
                                                 cef_gesture_event_callback_t*
                                                     s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefGestureEventCallbackCppToC,
                                   CefGestureEventCallback,
                                   cef_gesture_event_callback_t>::kWrapperType =
    WT_GESTURE_EVENT_CALLBACK;
