// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=deed69ac2f592e7589e4ab6eb7b72b92a64760ba$
//

#include "libcef_dll/cpptoc/get_saved_passwords_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"
#include "libcef_dll/transfer_util.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK get_saved_passwords_callback_on_complete(
    struct _cef_get_saved_passwords_callback_t* self,
    cef_string_list_t url,
    cef_string_list_t username) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return;
  // Verify param: url; type: string_vec_byref_const
  DCHECK(url);
  if (!url)
    return;
  // Verify param: username; type: string_vec_byref_const
  DCHECK(username);
  if (!username)
    return;

  // Translate param: url; type: string_vec_byref_const
  std::vector<CefString> urlList;
  transfer_string_list_contents(url, urlList);
  // Translate param: username; type: string_vec_byref_const
  std::vector<CefString> usernameList;
  transfer_string_list_contents(username, usernameList);

  // Execute
  CefGetSavedPasswordsCallbackCppToC::Get(self)->OnComplete(urlList,
                                                            usernameList);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefGetSavedPasswordsCallbackCppToC::CefGetSavedPasswordsCallbackCppToC() {
  GetStruct()->on_complete = get_saved_passwords_callback_on_complete;
}

// DESTRUCTOR - Do not edit by hand.

CefGetSavedPasswordsCallbackCppToC::~CefGetSavedPasswordsCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefGetSavedPasswordsCallback>
CefCppToCRefCounted<CefGetSavedPasswordsCallbackCppToC,
                    CefGetSavedPasswordsCallback,
                    cef_get_saved_passwords_callback_t>::
    UnwrapDerived(CefWrapperType type, cef_get_saved_passwords_callback_t* s) {
  NOTREACHED() << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCppToCRefCounted<CefGetSavedPasswordsCallbackCppToC,
                        CefGetSavedPasswordsCallback,
                        cef_get_saved_passwords_callback_t>::kWrapperType =
        WT_GET_SAVED_PASSWORDS_CALLBACK;
