// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=bc70acf47e067818a2c01f65c319bca589af931c$
//

#include "libcef_dll/cpptoc/get_origins_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"
#include "libcef_dll/transfer_util.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
get_origins_callback_on_origins(struct _cef_get_origins_callback_t* self,
                                cef_string_list_t origins) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: origins; type: string_vec_byref
  DCHECK(origins);
  if (!origins) {
    return;
  }

  // Translate param: origins; type: string_vec_byref
  std::vector<CefString> originsList;
  transfer_string_list_contents(origins, originsList);

  // Execute
  CefGetOriginsCallbackCppToC::Get(self)->OnOrigins(originsList);

  // Restore param: origins; type: string_vec_byref
  cef_string_list_clear(origins);
  transfer_string_list_contents(originsList, origins);
}

void CEF_CALLBACK
get_origins_callback_on_usages(struct _cef_get_origins_callback_t* self,
                               cef_string_list_t usages) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: usages; type: string_vec_byref
  DCHECK(usages);
  if (!usages) {
    return;
  }

  // Translate param: usages; type: string_vec_byref
  std::vector<CefString> usagesList;
  transfer_string_list_contents(usages, usagesList);

  // Execute
  CefGetOriginsCallbackCppToC::Get(self)->OnUsages(usagesList);

  // Restore param: usages; type: string_vec_byref
  cef_string_list_clear(usages);
  transfer_string_list_contents(usagesList, usages);
}

void CEF_CALLBACK
get_origins_callback_on_quotas(struct _cef_get_origins_callback_t* self,
                               cef_string_list_t quotas) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: quotas; type: string_vec_byref
  DCHECK(quotas);
  if (!quotas) {
    return;
  }

  // Translate param: quotas; type: string_vec_byref
  std::vector<CefString> quotasList;
  transfer_string_list_contents(quotas, quotasList);

  // Execute
  CefGetOriginsCallbackCppToC::Get(self)->OnQuotas(quotasList);

  // Restore param: quotas; type: string_vec_byref
  cef_string_list_clear(quotas);
  transfer_string_list_contents(quotasList, quotas);
}

void CEF_CALLBACK
get_origins_callback_on_complete(struct _cef_get_origins_callback_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefGetOriginsCallbackCppToC::Get(self)->OnComplete();
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefGetOriginsCallbackCppToC::CefGetOriginsCallbackCppToC() {
  GetStruct()->on_origins = get_origins_callback_on_origins;
  GetStruct()->on_usages = get_origins_callback_on_usages;
  GetStruct()->on_quotas = get_origins_callback_on_quotas;
  GetStruct()->on_complete = get_origins_callback_on_complete;
}

// DESTRUCTOR - Do not edit by hand.

CefGetOriginsCallbackCppToC::~CefGetOriginsCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefGetOriginsCallback> CefCppToCRefCounted<
    CefGetOriginsCallbackCppToC,
    CefGetOriginsCallback,
    cef_get_origins_callback_t>::UnwrapDerived(CefWrapperType type,
                                               cef_get_origins_callback_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefGetOriginsCallbackCppToC,
                                   CefGetOriginsCallback,
                                   cef_get_origins_callback_t>::kWrapperType =
    WT_GET_ORIGINS_CALLBACK;
