// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c2175f01b8450498987fae5ba37ca06b239b61a2$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_GET_ORIGIN_USAGE_OR_QUOTA_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_GET_ORIGIN_USAGE_OR_QUOTA_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_web_storage_capi.h"
#include "include/cef_web_storage.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefGetOriginUsageOrQuotaCallbackCppToC
    : public CefCppToCRefCounted<CefGetOriginUsageOrQuotaCallbackCppToC,
                                 CefGetOriginUsageOrQuotaCallback,
                                 cef_get_origin_usage_or_quota_callback_t> {
 public:
  CefGetOriginUsageOrQuotaCallbackCppToC();
  virtual ~CefGetOriginUsageOrQuotaCallbackCppToC();
};

#endif  // CEF_LIBCEF_DLL_CPPTOC_GET_ORIGIN_USAGE_OR_QUOTA_CALLBACK_CPPTOC_H_
