// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=8aaee2cf300843a14fd130a13f7217928262948e$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_INFO_BAR_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_INFO_BAR_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_devtools_message_handler_delegate_capi.h"
#include "include/cef_devtools_message_handler_delegate.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class CefInfoBarCallbackCppToC
    : public CefCppToCRefCounted<CefInfoBarCallbackCppToC,
                                 CefInfoBarCallback,
                                 cef_info_bar_callback_t> {
 public:
  CefInfoBarCallbackCppToC();
  virtual ~CefInfoBarCallbackCppToC();
};

#endif  // CEF_LIBCEF_DLL_CPPTOC_INFO_BAR_CALLBACK_CPPTOC_H_
