// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=4cce16b76f5c5f2c6b59bc0d35af86dce0fb88f5$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_LARGEST_CONTENTFUL_PAINT_DETAILS_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_LARGEST_CONTENTFUL_PAINT_DETAILS_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/cef_largest_contentful_paint_details_capi.h"
#include "include/cef_largest_contentful_paint_details.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class CefLargestContentfulPaintDetailsCppToC
    : public CefCppToCRefCounted<CefLargestContentfulPaintDetailsCppToC,
                                 CefLargestContentfulPaintDetails,
                                 cef_largest_contentful_paint_details_t> {
 public:
  CefLargestContentfulPaintDetailsCppToC();
  virtual ~CefLargestContentfulPaintDetailsCppToC();
};

#endif  // CEF_LIBCEF_DLL_CPPTOC_LARGEST_CONTENTFUL_PAINT_DETAILS_CPPTOC_H_