// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=20a76406e3ef0ddd234a22102af129aa1893dbc5$
//

#include "libcef_dll/cpptoc/largest_contentful_paint_details_cpptoc.h"

#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

int64_t CEF_CALLBACK largest_contentful_paint_details_get_navigation_start_time(
    struct _cef_largest_contentful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int64_t _retval = CefLargestContentfulPaintDetailsCppToC::Get(self)
                        ->GetNavigationStartTime();

  // Return type: simple
  return _retval;
}

int64_t CEF_CALLBACK
largest_contentful_paint_details_get_largest_image_paint_time(
    struct _cef_largest_contentful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int64_t _retval = CefLargestContentfulPaintDetailsCppToC::Get(self)
                        ->GetLargestImagePaintTime();

  // Return type: simple
  return _retval;
}

int64_t CEF_CALLBACK
largest_contentful_paint_details_get_largest_text_paint_time(
    struct _cef_largest_contentful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int64_t _retval = CefLargestContentfulPaintDetailsCppToC::Get(self)
                        ->GetLargestTextPaintTime();

  // Return type: simple
  return _retval;
}

int64_t CEF_CALLBACK
largest_contentful_paint_details_get_largest_image_load_start_time(
    struct _cef_largest_contentful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int64_t _retval = CefLargestContentfulPaintDetailsCppToC::Get(self)
                        ->GetLargestImageLoadStartTime();

  // Return type: simple
  return _retval;
}

int64_t CEF_CALLBACK
largest_contentful_paint_details_get_largest_image_load_end_time(
    struct _cef_largest_contentful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  int64_t _retval = CefLargestContentfulPaintDetailsCppToC::Get(self)
                        ->GetLargestImageLoadEndTime();

  // Return type: simple
  return _retval;
}

double_t CEF_CALLBACK largest_contentful_paint_details_get_image_bpp(
    struct _cef_largest_contentful_paint_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  double_t _retval =
      CefLargestContentfulPaintDetailsCppToC::Get(self)->GetImageBPP();

  // Return type: simple
  return _retval;
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefLargestContentfulPaintDetailsCppToC::
    CefLargestContentfulPaintDetailsCppToC() {
  GetStruct()->get_navigation_start_time =
      largest_contentful_paint_details_get_navigation_start_time;
  GetStruct()->get_largest_image_paint_time =
      largest_contentful_paint_details_get_largest_image_paint_time;
  GetStruct()->get_largest_text_paint_time =
      largest_contentful_paint_details_get_largest_text_paint_time;
  GetStruct()->get_largest_image_load_start_time =
      largest_contentful_paint_details_get_largest_image_load_start_time;
  GetStruct()->get_largest_image_load_end_time =
      largest_contentful_paint_details_get_largest_image_load_end_time;
  GetStruct()->get_image_bpp = largest_contentful_paint_details_get_image_bpp;
}

// DESTRUCTOR - Do not edit by hand.

CefLargestContentfulPaintDetailsCppToC::
    ~CefLargestContentfulPaintDetailsCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefLargestContentfulPaintDetails>
CefCppToCRefCounted<CefLargestContentfulPaintDetailsCppToC,
                    CefLargestContentfulPaintDetails,
                    cef_largest_contentful_paint_details_t>::
    UnwrapDerived(CefWrapperType type,
                  cef_largest_contentful_paint_details_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCppToCRefCounted<CefLargestContentfulPaintDetailsCppToC,
                        CefLargestContentfulPaintDetails,
                        cef_largest_contentful_paint_details_t>::kWrapperType =
        WT_LARGEST_CONTENTFUL_PAINT_DETAILS;
