// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=ba7670c595854058ccb4e00d10bad87a34e746fd$
//

#include "libcef_dll/cpptoc/load_committed_details_cpptoc.h"

#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

int CEF_CALLBACK load_committed_details_is_main_frame(
    struct _cef_load_committed_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  bool _retval = CefLoadCommittedDetailsCppToC::Get(self)->IsMainFrame();

  // Return type: bool
  return _retval;
}

int CEF_CALLBACK load_committed_details_is_same_document(
    struct _cef_load_committed_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  bool _retval = CefLoadCommittedDetailsCppToC::Get(self)->IsSameDocument();

  // Return type: bool
  return _retval;
}

int CEF_CALLBACK load_committed_details_did_replace_entry(
    struct _cef_load_committed_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return 0;
  }

  // Execute
  bool _retval = CefLoadCommittedDetailsCppToC::Get(self)->DidReplaceEntry();

  // Return type: bool
  return _retval;
}

cef_navigation_entry_type_t CEF_CALLBACK
load_committed_details_get_navigation_type(
    struct _cef_load_committed_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return NAVIGATION_TYPE_UNKNOWN;
  }

  // Execute
  cef_navigation_entry_type_t _retval =
      CefLoadCommittedDetailsCppToC::Get(self)->GetNavigationType();

  // Return type: simple
  return _retval;
}

cef_string_userfree_t CEF_CALLBACK load_committed_details_get_current_url(
    struct _cef_load_committed_details_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return NULL;
  }

  // Execute
  CefString _retval = CefLoadCommittedDetailsCppToC::Get(self)->GetCurrentURL();

  // Return type: string
  return _retval.DetachToUserFree();
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefLoadCommittedDetailsCppToC::CefLoadCommittedDetailsCppToC() {
  GetStruct()->is_main_frame = load_committed_details_is_main_frame;
  GetStruct()->is_same_document = load_committed_details_is_same_document;
  GetStruct()->did_replace_entry = load_committed_details_did_replace_entry;
  GetStruct()->get_navigation_type = load_committed_details_get_navigation_type;
  GetStruct()->get_current_url = load_committed_details_get_current_url;
}

// DESTRUCTOR - Do not edit by hand.

CefLoadCommittedDetailsCppToC::~CefLoadCommittedDetailsCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefLoadCommittedDetails> CefCppToCRefCounted<
    CefLoadCommittedDetailsCppToC,
    CefLoadCommittedDetails,
    cef_load_committed_details_t>::UnwrapDerived(CefWrapperType type,
                                                 cef_load_committed_details_t*
                                                     s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefLoadCommittedDetailsCppToC,
                                   CefLoadCommittedDetails,
                                   cef_load_committed_details_t>::kWrapperType =
    WT_LOAD_COMMITTED_DETAILS;
