// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c5eac1a1ca6bfc65cd343175a33cc88b39f0b4de$
//

#include "libcef_dll/cpptoc/permission_request_cpptoc.h"
#include "libcef_dll/ctocpp/access_request_ctocpp.h"
#include "libcef_dll/ctocpp/screen_capture_access_request_ctocpp.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
permission_request_on_geolocation_show(struct _cef_permission_request_t* self,
                                       const cef_string_t* origin) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: origin; type: string_byref_const
  DCHECK(origin);
  if (!origin) {
    return;
  }

  // Execute
  CefPermissionRequestCppToC::Get(self)->OnGeolocationShow(CefString(origin));
}

void CEF_CALLBACK
permission_request_on_geolocation_hide(struct _cef_permission_request_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefPermissionRequestCppToC::Get(self)->OnGeolocationHide();
}

void CEF_CALLBACK
permission_request_on_permission_request(struct _cef_permission_request_t* self,
                                         cef_access_request_t* request) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: request; type: refptr_diff
  DCHECK(request);
  if (!request) {
    return;
  }

  // Execute
  CefPermissionRequestCppToC::Get(self)->OnPermissionRequest(
      CefAccessRequestCToCpp::Wrap(request));
}

void CEF_CALLBACK permission_request_on_permission_request_canceled(
    struct _cef_permission_request_t* self,
    cef_access_request_t* request) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: request; type: refptr_diff
  DCHECK(request);
  if (!request) {
    return;
  }

  // Execute
  CefPermissionRequestCppToC::Get(self)->OnPermissionRequestCanceled(
      CefAccessRequestCToCpp::Wrap(request));
}

void CEF_CALLBACK permission_request_on_screen_capture_request(
    struct _cef_permission_request_t* self,
    cef_screen_capture_access_request_t* request) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: request; type: refptr_diff
  DCHECK(request);
  if (!request) {
    return;
  }

  // Execute
  CefPermissionRequestCppToC::Get(self)->OnScreenCaptureRequest(
      CefScreenCaptureAccessRequestCToCpp::Wrap(request));
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefPermissionRequestCppToC::CefPermissionRequestCppToC() {
  GetStruct()->on_geolocation_show = permission_request_on_geolocation_show;
  GetStruct()->on_geolocation_hide = permission_request_on_geolocation_hide;
  GetStruct()->on_permission_request = permission_request_on_permission_request;
  GetStruct()->on_permission_request_canceled =
      permission_request_on_permission_request_canceled;
  GetStruct()->on_screen_capture_request =
      permission_request_on_screen_capture_request;
}

// DESTRUCTOR - Do not edit by hand.

CefPermissionRequestCppToC::~CefPermissionRequestCppToC() {}

template <>
CefRefPtr<CefPermissionRequest> CefCppToCRefCounted<
    CefPermissionRequestCppToC,
    CefPermissionRequest,
    cef_permission_request_t>::UnwrapDerived(CefWrapperType type,
                                             cef_permission_request_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefPermissionRequestCppToC,
                                   CefPermissionRequest,
                                   cef_permission_request_t>::kWrapperType =
    WT_PERMISSION_REQUEST;
