// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=494e1e0011435fea65d092fe7ef6522ea9a39254$
//

#include "libcef_dll/cpptoc/post_data_stream_init_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK post_data_stream_init_callback_cont(
    struct _cef_post_data_stream_init_callback_t* self,
    int result) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefPostDataStreamInitCallbackCppToC::Get(self)->OnInitComplete(result);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefPostDataStreamInitCallbackCppToC::CefPostDataStreamInitCallbackCppToC() {
  GetStruct()->cont = post_data_stream_init_callback_cont;
}

// DESTRUCTOR - Do not edit by hand.

CefPostDataStreamInitCallbackCppToC::~CefPostDataStreamInitCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefPostDataStreamInitCallback>
CefCppToCRefCounted<CefPostDataStreamInitCallbackCppToC,
                    CefPostDataStreamInitCallback,
                    cef_post_data_stream_init_callback_t>::
    UnwrapDerived(CefWrapperType type,
                  cef_post_data_stream_init_callback_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType
    CefCppToCRefCounted<CefPostDataStreamInitCallbackCppToC,
                        CefPostDataStreamInitCallback,
                        cef_post_data_stream_init_callback_t>::kWrapperType =
        WT_POST_DATA_STREAM_INIT_CALLBACK;
