// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=ce6d628f37ca565603cb5d9da6a2812615ce3439$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_REQUEST_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_REQUEST_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_request.h"
#include "include/capi/cef_request_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefRequest_0_CppToC
    : public CefCppToCRefCounted<CefRequest_0_CppToC, CefRequest, cef_request_0_t> {
 public:
  CefRequest_0_CppToC();
  virtual ~CefRequest_0_CppToC();
};

constexpr auto CefRequestCppToC_Wrap = CefRequest_0_CppToC::Wrap;
constexpr auto CefRequestCppToC_Unwrap = CefRequest_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_REQUEST_CPPTOC_H_
