// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=fea8112fe820c583d240bedaee379e1c9c1d24e7$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_RUN_QUICK_MENU_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_RUN_QUICK_MENU_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_context_menu_handler.h"
#include "include/capi/cef_context_menu_handler_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefRunQuickMenuCallback_0_CppToC
    : public CefCppToCRefCounted<CefRunQuickMenuCallback_0_CppToC, CefRunQuickMenuCallback, cef_run_quick_menu_callback_0_t> {
 public:
  CefRunQuickMenuCallback_0_CppToC();
  virtual ~CefRunQuickMenuCallback_0_CppToC();
};

constexpr auto CefRunQuickMenuCallbackCppToC_Wrap = CefRunQuickMenuCallback_0_CppToC::Wrap;
constexpr auto CefRunQuickMenuCallbackCppToC_Unwrap = CefRunQuickMenuCallback_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_RUN_QUICK_MENU_CALLBACK_CPPTOC_H_
