// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=991b8b66513d85cb57a7ccdc33f67502ab0d9be2$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_SCREEN_CAPTURE_CALLBACK_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_SCREEN_CAPTURE_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_browser_capi.h"
#include "include/capi/cef_client_capi.h"
#include "include/cef_browser.h"
#include "include/cef_client.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefScreenCaptureCallbackCppToC
    : public CefCppToCRefCounted<CefScreenCaptureCallbackCppToC,
                                 CefScreenCaptureCallback,
                                 cef_screen_capture_callback_t> {
 public:
  CefScreenCaptureCallbackCppToC();
  virtual ~CefScreenCaptureCallbackCppToC();
};

#endif  // CEF_LIBCEF_DLL_CPPTOC_SCREEN_CAPTURE_CALLBACK_CPPTOC_H_
