// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c333c270503528a3318f3e9a538540b3eb3f0d61$
//

#include "libcef_dll/cpptoc/select_popup_callback_cpptoc.h"

#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
select_popup_callback_cont(struct _cef_select_popup_callback_t* self,
                           size_t indicesCount,
                           int const* indices) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: indices; type: simple_vec_byref_const
  DCHECK(indicesCount == 0 || indices);
  if (indicesCount > 0 && !indices) {
    return;
  }

  // Translate param: indices; type: simple_vec_byref_const
  std::vector<int> indicesList;
  if (indicesCount > 0) {
    for (size_t i = 0; i < indicesCount; ++i) {
      int indicesVal = indices[i];
      indicesList.push_back(indicesVal);
    }
  }

  // Execute
  CefSelectPopupCallbackCppToC::Get(self)->Continue(indicesList);
}

void CEF_CALLBACK
select_popup_callback_cancel(struct _cef_select_popup_callback_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefSelectPopupCallbackCppToC::Get(self)->Cancel();
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefSelectPopupCallbackCppToC::CefSelectPopupCallbackCppToC() {
  GetStruct()->cont = select_popup_callback_cont;
  GetStruct()->cancel = select_popup_callback_cancel;
}

// DESTRUCTOR - Do not edit by hand.

CefSelectPopupCallbackCppToC::~CefSelectPopupCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefSelectPopupCallback> CefCppToCRefCounted<
    CefSelectPopupCallbackCppToC,
    CefSelectPopupCallback,
    cef_select_popup_callback_t>::UnwrapDerived(CefWrapperType type,
                                                cef_select_popup_callback_t*
                                                    s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<CefSelectPopupCallbackCppToC,
                                   CefSelectPopupCallback,
                                   cef_select_popup_callback_t>::kWrapperType =
    WT_SELECT_POPUP_CALLBACK;
