// Copyright (c) 2024 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f6a610c87ad81581de761abe2e1c08332d81ac42$
//

#include "libcef_dll/cpptoc/select_client_certificate_callback_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK select_client_certificate_callback_select(
    struct _cef_select_client_certificate_callback_t* self,
    const cef_string_t* private_key_file,
    const cef_string_t* cert_chain_file) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }
  // Verify param: private_key_file; type: string_byref_const
  DCHECK(private_key_file);
  if (!private_key_file) {
    return;
  }
  // Verify param: cert_chain_file; type: string_byref_const
  DCHECK(cert_chain_file);
  if (!cert_chain_file) {
    return;
  }

  // Execute
  CefSelectClientCertificateCallbackCppToC::Get(self)->Select(
      CefString(private_key_file), CefString(cert_chain_file));
}

void CEF_CALLBACK select_client_certificate_callback_cancel(
    struct _cef_select_client_certificate_callback_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefSelectClientCertificateCallbackCppToC::Get(self)->Cancel();
}

void CEF_CALLBACK select_client_certificate_callback_ignore(
    struct _cef_select_client_certificate_callback_t* self) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self) {
    return;
  }

  // Execute
  CefSelectClientCertificateCallbackCppToC::Get(self)->Ignore();
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefSelectClientCertificateCallbackCppToC::
    CefSelectClientCertificateCallbackCppToC() {
  GetStruct()->select = select_client_certificate_callback_select;
  GetStruct()->cancel = select_client_certificate_callback_cancel;
  GetStruct()->ignore = select_client_certificate_callback_ignore;
}

// DESTRUCTOR - Do not edit by hand.

CefSelectClientCertificateCallbackCppToC::
    ~CefSelectClientCertificateCallbackCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefSelectClientCertificateCallback>
CefCppToCRefCounted<CefSelectClientCertificateCallbackCppToC,
                    CefSelectClientCertificateCallback,
                    cef_select_client_certificate_callback_t>::
    UnwrapDerived(CefWrapperType type,
                  cef_select_client_certificate_callback_t* s) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
CefWrapperType CefCppToCRefCounted<
    CefSelectClientCertificateCallbackCppToC,
    CefSelectClientCertificateCallback,
    cef_select_client_certificate_callback_t>::kWrapperType =
    WT_SELECT_CLIENT_CERTIFICATE_CALLBACK;
