// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=23dd3f01f4928cbf675985c107f56df21a997276$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_TASK_RUNNER_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_TASK_RUNNER_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_task.h"
#include "include/capi/cef_task_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefTaskRunner_0_CppToC
    : public CefCppToCRefCounted<CefTaskRunner_0_CppToC, CefTaskRunner, cef_task_runner_0_t> {
 public:
  CefTaskRunner_0_CppToC();
  virtual ~CefTaskRunner_0_CppToC();
};

constexpr auto CefTaskRunnerCppToC_Wrap = CefTaskRunner_0_CppToC::Wrap;
constexpr auto CefTaskRunnerCppToC_Unwrap = CefTaskRunner_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_TASK_RUNNER_CPPTOC_H_
