// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=587a0e89594be121e853395e05c5e13ee93b3d7c$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_V8_EXCEPTION_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_V8_EXCEPTION_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_v8.h"
#include "include/capi/cef_v8_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefV8Exception_0_CppToC
    : public CefCppToCRefCounted<CefV8Exception_0_CppToC, CefV8Exception, cef_v8_exception_0_t> {
 public:
  CefV8Exception_0_CppToC();
  virtual ~CefV8Exception_0_CppToC();
};

constexpr auto CefV8ExceptionCppToC_Wrap = CefV8Exception_0_CppToC::Wrap;
constexpr auto CefV8ExceptionCppToC_Unwrap = CefV8Exception_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_V8_EXCEPTION_CPPTOC_H_
