// Copyright (c) 2025 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7da11f04d68981c9c3873b11df1fb6d0a60c712f$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_VALUE_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_VALUE_CPPTOC_H_
#pragma once

#if !defined(BUILDING_CEF_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/cef_values.h"
#include "include/capi/cef_values_capi_versions.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure at API version 0.
// This class may be instantiated and accessed DLL-side only.
class CefValue_0_CppToC
    : public CefCppToCRefCounted<CefValue_0_CppToC, CefValue, cef_value_0_t> {
 public:
  CefValue_0_CppToC();
  virtual ~CefValue_0_CppToC();
};

constexpr auto CefValueCppToC_Wrap = CefValue_0_CppToC::Wrap;
constexpr auto CefValueCppToC_Unwrap = CefValue_0_CppToC::Unwrap;

#endif  // CEF_LIBCEF_DLL_CPPTOC_VALUE_CPPTOC_H_
